version: '3.7'
services:
  api:
    image: ${DOCKER_IMAGE:-ac-api}:${DOCKER_TAG:-latest}
    ports:
      - ${HTTP_PORT:-8080}:${HTTP_PORT:-8080}
    environment:
      HTTP_PORT: ${HTTP_PORT:-8080}
      GUNICORN_BIND_ADDRESS: ${GUNICORN_BIND_ADDRESS:-0.0.0.0:${HTTP_PORT:-8080}}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-4}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-360}
      GM_USERNAME: ${GM_USERNAME:?Required GM_USERNAME}
      GM_PASSWORD: ${GM_USERNAME:?Required GM_PASSWORD}
      AZEROTHCORE_REMOTE_ADDRESS: ${AZEROTHCORE_REMOTE_ADDRESS:?Required AZEROTHCORE_REMOTE_ADDRESS}
    restart: on-failure
