-- Ensure we are using the characters database
USE `acore_characters`;

-- Create the trivia_leaderboard table if it doesn't already exist
CREATE TABLE IF NOT EXISTS `trivia_leaderboard` (
  `name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `points` int DEFAULT NULL,
  `streak` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

DELETE FROM `trivia_leaderboard`;

-- Create the trivia_questions table if it doesn't already exist
CREATE TABLE IF NOT EXISTS `trivia_questions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `question` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `answer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `points` int DEFAULT '0',
  `difficulty` enum('easy','medium','hard') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'easy',
  `category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=662 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- SQL Dump for `trivia_questions`
DELETE FROM `trivia_questions`;
INSERT INTO `trivia_questions` (`id`, `question`, `answer`, `points`, `difficulty`, `category`) VALUES
	(1, 'What is the name of the human capital city in World of Warcraft?', 'Stormwind', 2, 'easy', 'City'),
	(2, 'Which race starts in the zone of Elwynn Forest?', 'Human', 2, 'easy', 'Zone'),
	(3, 'Which class can begin wearing plate armor at level 40?', 'Warrior', 3, 'easy', 'Class'),
	(4, 'What is the name of the Horde\'s capital city located in Durotar?', 'Orgrimmar', 3, 'easy', 'City'),
	(5, 'Which zone is known for the Alliance stronghold, Ironforge?', 'Dun Morogh', 4, 'easy', 'Zone'),
	(6, 'Who is the leader of the Alliance during the events of WotLK?', 'King Varian Wrynn', 3, 'easy', 'Lore'),
	(7, 'Which class can use the spell "Frostbolt"?', 'Mage', 1, 'easy', 'Class'),
	(8, 'What is the name of the dwarf starting zone?', 'Dun Morogh', 3, 'easy', 'Zone'),
	(9, 'Which class is known for their ability to stealth and pick locks?', 'Rogue', 3, 'easy', 'Class'),
	(11, 'Which race starts in the zone of Teldrassil?', 'Night Elf', 3, 'easy', 'Zone'),
	(12, 'What is the original capital city of the Gnomes before it was overrun by troggs?', 'Gnomeregan', 5, 'medium', 'City'),
	(13, 'Who is the Warchief of the Horde during WotLK?', 'Thrall', 3, 'easy', 'Lore'),
	(14, 'Which zone is home to the city of Stormwind?', 'Elwynn Forest', 2, 'easy', 'Zone'),
	(15, 'Which zone is known for the starting area of Blood Elves?', 'Eversong Woods', 4, 'easy', 'Zone'),
	(16, 'Which class can wear only cloth armor?', 'Mage', 3, 'easy', 'Class'),
	(17, 'Which city is known as the "City of Mages"?', 'Dalaran', 3, 'easy', 'City'),
	(18, 'Which race is associated with the city of Silvermoon?', 'Blood Elf', 5, 'easy', 'Race'),
	(19, 'What is the name of the portal that connects Azeroth to Outland?', 'The Dark Portal', 4, 'easy', 'Lore'),
	(20, 'Which zone is known for its lush forests and Night Elf ruins?', 'Ashenvale', 3, 'easy', 'Zone'),
	(21, 'Who is the leader of the Night Elves during the events of WotLK?', 'Tyrande Whisperwind', 4, 'easy', 'Lore'),
	(22, 'Which faction does the Draenei belong to?', 'Alliance', 2, 'easy', 'Faction'),
	(23, 'Which zone is home to the Scarlet Monastery?', 'Tirisfal Glades', 3, 'easy', 'Zone'),
	(24, 'Which race is known for their engineering skills?', 'Gnomes', 5, 'easy', 'Race'),
	(25, 'Which race starts in the Valley of Trials?', 'Orc', 3, 'easy', 'Zone'),
	(26, 'Who is the king of Ironforge during WotLK?', 'Magni Bronzebeard', 3, 'easy', 'Lore'),
	(27, 'Which zone contains the city of Orgrimmar?', 'Durotar', 3, 'easy', 'Zone'),
	(28, 'Which faction does the Orc race belong to?', 'Horde', 2, 'easy', 'Faction'),
	(29, 'Which class can use the ability "Heroic Strike"?', 'Warrior', 2, 'easy', 'Class'),
	(30, 'Who is the leader of the Forsaken during the events of WotLK?', 'Sylvanas Windrunner', 3, 'easy', 'Lore'),
	(31, 'Which race is known for their racial ability "War Stomp"?', 'Tauren', 3, 'easy', 'Race'),
	(32, 'Which race has the racial ability "Shadowmeld"?', 'Night Elf', 3, 'easy', 'Race'),
	(33, 'Which faction is the main enemy of the Scourge?', 'Argent Crusade', 4, 'easy', 'Faction'),
	(34, 'Which zone in Northrend is home to the Scourge stronghold of Icecrown Citadel?', 'Icecrown', 3, 'easy', 'Zone'),
	(35, 'Which class can summon demons to aid them in combat?', 'Warlock', 2, 'easy', 'Class'),
	(36, 'Which city serves as a neutral hub for both Horde and Alliance players in Outland?', 'Shattrath City', 3, 'easy', 'City'),
	(37, 'Which dungeon features the boss Edwin VanCleef?', 'The Deadmines', 3, 'easy', 'Dungeon'),
	(38, 'Which zone is home to the Argent Tournament grounds in WotLK?', 'Icecrown', 3, 'easy', 'Zone'),
	(39, 'What is the name of the faction led by Highlord Tirion Fordring?', 'Argent Crusade', 5, 'easy', 'Faction'),
	(40, 'Which class can use the ability "Divine Shield"?', 'Paladin', 3, 'easy', 'Class'),
	(41, 'Which city on the Azuremyst Isles serves as the crash site of the Draenei spaceship?', 'The Exodar', 5, 'easy', 'City'),
	(42, 'Which raid in WotLK is known for the Old God Yogg-Saron?', 'Ulduar', 3, 'easy', 'Raid'),
	(43, 'Who is the leader of the Blood Elves during the events of WotLK?', 'Lor\'themar Theron', 3, 'easy', 'Lore'),
	(44, 'What is the name of the large forested zone in Kalimdor that contains ancient ruins?', 'Ashenvale', 4, 'easy', 'Zone'),
	(45, 'Which class can use the ability "Rebirth", allowing them to resurrect allies during combat?', 'Druid', 3, 'easy', 'Class'),
	(46, 'Who is the leader of the Red Dragonflight in WotLK?', 'Alexstrasza', 5, 'easy', 'Lore'),
	(47, 'Which zone in Outland is home to the Black Temple?', 'Shadowmoon Valley', 3, 'easy', 'Zone'),
	(48, 'What is the name of the orc warchief who founded Orgrimmar?', 'Thrall', 3, 'easy', 'Lore'),
	(49, 'Which class uses the ability "Mortal Strike"?', 'Warrior', 2, 'easy', 'Class'),
	(50, 'What is the name of the orc warchief who wielded the Doomhammer before Thrall?', 'Orgrim Doomhammer', 3, 'easy', 'Lore'),
	(51, 'Which race starts in the zone of Durotar?', 'Orc', 3, 'easy', 'Zone'),
	(52, 'Who is the final boss of the Naxxramas raid in WotLK?', 'Kel\'Thuzad', 4, 'easy', 'Raid'),
	(53, 'Which race has the racial ability "Stoneform"?', 'Dwarf', 3, 'easy', 'Race'),
	(54, 'Which faction is based in the city of Darnassus?', 'Night Elves', 3, 'easy', 'Faction'),
	(55, 'Which Titan-forged guardian betrayed the keepers of Ulduar and enabled the corruption of Yogg-Saron?', 'Loken', 6, 'hard', 'Lore'),
	(56, 'Which dungeon in Outland features the boss Keli\'dan the Breaker?', 'Hellfire Ramparts', 3, 'easy', 'Dungeon'),
	(57, 'Who is the dragon aspect of the Bronze Dragonflight?', 'Nozdormu', 4, 'easy', 'Lore'),
	(58, 'Which shadow-based spell allows Priests to deal damage over time?', 'Shadow Word: Pain', 3, 'medium', 'Class'),
	(59, 'Which zone in Kalimdor contains the Caverns of Time?', 'Tanaris', 3, 'easy', 'Zone'),
	(60, 'Which faction in Shattrath City opposes the Burning Legion?', 'Aldor', 3, 'easy', 'Faction'),
	(61, 'Who is the leader of the Argent Crusade?', 'Tirion Fordring', 3, 'easy', 'Faction'),
	(62, 'Which race has the racial ability "Escape Artist"?', 'Gnome', 3, 'easy', 'Race'),
	(63, 'Which class can use the spell "Chain Heal"?', 'Shaman', 3, 'easy', 'Class'),
	(64, 'Who is the final boss of the Black Temple?', 'Illidan Stormrage', 4, 'easy', 'Raid'),
	(65, 'Which faction is known for its animosity toward the Scourge?', 'Scarlet Crusade', 4, 'easy', 'Faction'),
	(66, 'What colossal machine roams Hellfire Peninsula, instilling fear into adventurers with its thundering footsteps?', 'Fel Reaver', 4, 'hard', 'Zone'),
	(68, 'Which zone in Northrend contains the Titan complex known as the Temple of Storms?', 'Storm Peaks', 6, 'medium', 'Zone'),
	(69, 'Who is the leader of the Kirin Tor during the events of WotLK?', 'Rhonin', 4, 'easy', 'Lore'),
	(70, 'Which class uses the spell "Healing Touch"?', 'Druid', 3, 'easy', 'Class'),
	(71, 'Which dungeon is located in the Western Plaguelands and is home to Darkmaster Gandling?', 'Scholomance', 6, 'medium', 'Dungeon'),
	(72, 'Which event marks the beginning of the Third War?', 'The Fall of Quel\'Thalas', 7, 'medium', 'Event'),
	(73, 'Who was the orc warlock responsible for the creation of the first Death Knights?', 'Gul\'dan', 7, 'medium', 'Lore'),
	(74, 'Which raid is located in Zangarmarsh and features Lady Vashj as the final boss?', 'Serpentshrine Cavern', 7, 'medium', 'Raid'),
	(75, 'Which zone in Northrend is home to the Titan complex known as Ulduar?', 'Storm Peaks', 6, 'medium', 'Zone'),
	(76, 'Which class in Vanilla WoW could initially only be played by the Tauren race on the Horde side?', 'Druid', 6, 'medium', 'Class'),
	(77, 'Who is the dragon aspect responsible for protecting time and leading the Bronze Dragonflight?', 'Nozdormu', 8, 'medium', 'Lore'),
	(78, 'Which faction is based in Shattrath City and opposes the Burning Legion?', 'The Aldor', 6, 'medium', 'Faction'),
	(79, 'What is the name of the Naaru who helps players in Shattrath City?', 'A\'dal', 7, 'medium', 'Lore'),
	(80, 'Who is the final boss of the Tempest Keep raid?', 'Kael\'thas Sunstrider', 7, 'medium', 'Raid'),
	(81, 'Which class can use the ability "Chain Lightning"?', 'Shaman', 4, 'medium', 'Class'),
	(82, 'Which raid boss in Naxxramas is known for spreading the necrotic plague?', 'Heigan the Unclean', 8, 'medium', 'Raid'),
	(84, 'Who was the leader of the Ebon Blade during the events of WotLK?', 'Darion Mograine', 7, 'medium', 'Lore'),
	(85, 'What group, led by Gul\'dan, was directly responsible for opening the Dark Portal during the First War?', 'Shadow Council', 7, 'medium', 'Lore'),
	(86, 'Who was the human mage who served as the last Guardian of Tirisfal before Medivh?', 'Aegwynn', 9, 'medium', 'Lore'),
	(87, 'Which zone in the Eastern Kingdoms is known for the Scarlet Monastery dungeon?', 'Tirisfal Glades', 6, 'medium', 'Zone'),
	(88, 'What is the name of the dungeon within the Caverns of Time where players assist Thrall?', 'The Culling of Stratholme', 7, 'medium', 'Dungeon'),
	(90, 'Which race introduced in The Burning Crusade can communicate with the Naaru?', 'Draenei', 8, 'medium', 'Race'),
	(91, 'What is the name of the blood elf capital city in the Eastern Kingdoms?', 'Silvermoon City', 6, 'medium', 'City'),
	(92, 'Which class can use the ability "Mind Control"?', 'Priest', 3, 'easy', 'Class'),
	(93, 'Which dungeon located in Hellfire Peninsula features the boss Keli\'dan the Breaker?', 'Hellfire Ramparts', 6, 'medium', 'Dungeon'),
	(94, 'Which faction did the Forsaken ally with during the events of Classic WoW?', 'The Horde', 6, 'medium', 'Faction'),
	(95, 'Which raid is known for its battle against the Old God Yogg-Saron?', 'Ulduar', 7, 'medium', 'Raid'),
	(96, 'Which race has the racial ability "Shadowmeld"?', 'Night Elf', 6, 'medium', 'Race'),
	(97, 'Which event allowed players to unlock the gates of Ahn\'Qiraj?', 'The Shifting Sands', 9, 'medium', 'Event'),
	(98, 'Which class has the ability to shapeshift into different animal forms?', 'Druid', 6, 'medium', 'Class'),
	(99, 'Who was the first wielder of the Ashbringer before it became corrupted?', 'Alexandros Mograine', 8, 'medium', 'Lore'),
	(100, 'Which zone in Northrend features the dungeon Utgarde Keep?', 'Howling Fjord', 6, 'medium', 'Zone'),
	(101, 'Which city serves as a neutral hub for both Alliance and Horde players in Outland?', 'Shattrath City', 6, 'medium', 'City'),
	(102, 'Who is the final boss of the Karazhan raid?', 'Prince Malchezaar', 7, 'medium', 'Raid'),
	(103, 'Which zone in Kalimdor is home to the Caverns of Time?', 'Tanaris', 6, 'medium', 'Zone'),
	(104, 'What is the name of the leader of the Scarlet Crusade?', 'Saidan Dathrohan', 7, 'medium', 'Lore'),
	(105, 'Which class has the ability "Death Grip"?', 'Death Knight', 6, 'medium', 'Class'),
	(106, 'What is the name of the leader of the Kirin Tor during WotLK?', 'Rhonin', 7, 'medium', 'Lore'),
	(107, 'Who was the leader of the Amani trolls during the events of Zul\'Aman?', 'Zul\'jin', 8, 'medium', 'Lore'),
	(108, 'Which raid is located in the Ghostlands and features the Amani trolls?', 'Zul\'Aman', 7, 'medium', 'Raid'),
	(109, 'Who is the final boss of the Serpentshrine Cavern raid?', 'Lady Vashj', 7, 'medium', 'Raid'),
	(110, 'Which dungeon is located in Blackrock Mountain and is home to General Drakkisath?', 'Upper Blackrock Spire', 7, 'medium', 'Dungeon'),
	(111, 'What is the name of the Titan construct found in the Storm Peaks?', 'Ulduar', 8, 'medium', 'Zone'),
	(112, 'Who is the leader of the Argent Crusade during WotLK?', 'Tirion Fordring', 7, 'medium', 'Faction'),
	(113, 'Which zone in Outland features the Cenarion Expedition and giant mushrooms?', 'Zangarmarsh', 6, 'medium', 'Zone'),
	(114, 'What is the name of the dragonflight responsible for safeguarding magic?', 'Blue Dragonflight', 6, 'medium', 'Lore'),
	(115, 'Which class has the ability "Rebirth," allowing them to resurrect players in combat?', 'Druid', 7, 'medium', 'Class'),
	(116, 'Who is the dragon aspect of the Red Dragonflight?', 'Alexstrasza', 7, 'medium', 'Lore'),
	(117, 'Which zone in Northrend is home to the Argent Tournament?', 'Icecrown', 6, 'medium', 'Zone'),
	(118, 'Which zone in Outland is home to the Black Temple?', 'Shadowmoon Valley', 6, 'medium', 'Zone'),
	(119, 'Which dungeon in WotLK features the boss Skadi the Ruthless?', 'Utgarde Pinnacle', 7, 'medium', 'Dungeon'),
	(120, 'What is the name of the ancient night elf city located beneath the Well of Eternity?', 'Zin-Azshari', 7, 'medium', 'Lore'),
	(121, 'Who was the first wielder of Frostmourne before becoming the Lich King?', 'Arthas Menethil', 9, 'hard', 'Lore'),
	(122, 'Which raid involves fighting the Old God C\'Thun?', 'Ahn\'Qiraj', 10, 'hard', 'Raid'),
	(123, 'Which Titan facility in Northrend was constructed to imprison powerful entities like Yogg-Saron?', 'Ulduar', 9, 'hard', 'Lore'),
	(124, 'Which faction is based in the Isle of Quel\'Danas?', 'Shattered Sun Offensive', 9, 'hard', 'Faction'),
	(125, 'Who is the final boss of the Sunwell Plateau raid?', 'Kil\'jaeden', 10, 'hard', 'Raid'),
	(126, 'Which zone is home to the Temple of Atal\'Hakkar?', 'Swamp of Sorrows', 8, 'hard', 'Zone'),
	(127, 'Which event is associated with the opening of the Gates of Ahn\'Qiraj?', 'The Shifting Sands', 9, 'hard', 'Event'),
	(128, 'Who is the dragon aspect of the Green Dragonflight?', 'Ysera', 8, 'hard', 'Lore'),
	(129, 'Which dungeon is home to the Avatar of Hakkar?', 'Sunken Temple', 9, 'hard', 'Dungeon'),
	(130, 'What is the name of the demon lord who created the orcish fel corruption?', 'Kil\'jaeden', 10, 'hard', 'Lore'),
	(131, 'Which raid boss is known for the phrase "YOU ARE NOT PREPARED!"?', 'Illidan Stormrage', 10, 'hard', 'Raid'),
	(132, 'Who betrayed the Night Elves by siding with Sargeras?', 'Queen Azshara', 9, 'hard', 'Lore'),
	(133, 'Which Old God is trapped beneath Ulduar?', 'Yogg-Saron', 9, 'hard', 'Lore'),
	(134, 'What is the name of the event that led to the Sundering of Azeroth?', 'The War of the Ancients', 9, 'hard', 'Event'),
	(135, 'Which powerful entity did the Dark Iron Dwarves originally serve after their defeat in the War of the Three Hammers?', 'Ragnaros', 8, 'hard', 'Lore'),
	(136, 'Who is the final boss of the Blackwing Lair raid?', 'Nefarian', 9, 'hard', 'Raid'),
	(137, 'Which legendary weapon is crafted using Shadowmourne fragments?', 'Shadowmourne', 10, 'hard', 'Items'),
	(138, 'Which raid boss drops the mount Ashes of Al\'ar?', 'Kael\'thas Sunstrider', 9, 'hard', 'Raid'),
	(139, 'Who was the first Guardian of Tirisfal?', 'Alodi', 10, 'hard', 'Lore'),
	(140, 'Which raid features the encounter with the Twin Emperors?', 'Ahn\'Qiraj', 9, 'hard', 'Raid'),
	(141, 'Which event led to the creation of the first Death Knights?', 'The Second War', 8, 'hard', 'Event'),
	(142, 'What is the name of the Naaru who was captured by the Blood Elves in Sunwell Plateau?', 'M\'uru', 9, 'hard', 'Lore'),
	(143, 'Who was the first Lich King before Arthas Menethil?', 'Ner\'zhul', 10, 'hard', 'Lore'),
	(144, 'Which troll empire was centered around Zul\'Aman?', 'Amani', 9, 'hard', 'Lore'),
	(145, 'What is the name of the undead zone that serves as the starting area for the Forsaken?', 'Tirisfal Glades', 8, 'hard', 'Zone'),
	(146, 'Which Titan ordered the creation of the Dragon Aspects?', 'Aman\'Thul', 10, 'hard', 'Lore'),
	(147, 'Which dungeon is located within Blackrock Mountain and features Emperor Thaurissan?', 'Blackrock Depths', 9, 'hard', 'Dungeon'),
	(148, 'Which zone contains the ruins of the ancient troll city of Zul\'Gurub?', 'Stranglethorn Vale', 9, 'hard', 'Zone'),
	(149, 'Who is the dragon aspect of the Blue Dragonflight?', 'Malygos', 9, 'hard', 'Lore'),
	(150, 'Who led the defense of Light\'s Hope Chapel against the Scourge?', 'Tirion Fordring', 9, 'hard', 'Lore'),
	(151, 'Which quest chain in Silithus leads to the opening of the Gates of Ahn\'Qiraj?', 'The Scepter of the Shifting Sands', 9, 'hard', 'Quests'),
	(152, 'What is the name of the quest where you help Thrall escape from Durnholde Keep?', 'Escape from Durnholde', 6, 'medium', 'Quests'),
	(153, 'Which daily quest hub is located on the Isle of Quel\'Danas?', 'Shattered Sun Offensive', 5, 'medium', 'Quests'),
	(154, 'Which quest rewards players with the key to Karazhan?', 'The Master\'s Key', 7, 'hard', 'Quests'),
	(155, 'Who gives the starting quest for the Onyxia Attunement chain for the Alliance?', 'Highlord Bolvar Fordragon', 8, 'hard', 'Quests'),
	(156, 'Which quest involves escorting an NPC named Pamela Redpath in Eastern Plaguelands?', 'Little Pamela', 6, 'medium', 'Quests'),
	(157, 'In Nagrand, what is the name of the quest chain where you help Thrall reunite with his grandmother?', 'The Hero of the Mag\'har', 7, 'medium', 'Quests'),
	(158, 'What is the name of the quest in Wailing Caverns that requires collecting Serpentbloom?', 'Cleansing the Caverns', 3, 'easy', 'Quests'),
	(159, 'Which quest chain leads to acquiring the legendary item Thunderfury?', 'Bindings of the Windseeker', 10, 'hard', 'Quests'),
	(160, 'What quest chain in Dragonblight involves working with Alexstrasza and the Wyrmrest Accord?', 'The Wrathgate', 8, 'hard', 'Quests'),
	(161, 'What is the name of the legendary healing mace from Ulduar?', 'Val\'anyr, Hammer of Ancient Kings', 10, 'hard', 'Items'),
	(162, 'Which item, dropped by Prince Thunderaan, is used to forge the legendary sword Thunderfury?', 'Dormant Wind Kissed Blade', 9, 'hard', 'Items'),
	(163, 'Which item is needed to summon Ragnaros in the Molten Core raid?', 'Aqual Quintessence', 7, 'hard', 'Items'),
	(164, 'What is the name of the trinket that allows underwater breathing and is obtained from Gnomeregan?', 'Hydrocane', 4, 'medium', 'Items'),
	(165, 'What item is required to summon the Headless Horseman during the Hallow\'s End event?', 'Dreary Candle', 6, 'medium', 'Items'),
	(166, 'What is the name of the necklace used to teleport to Dalaran in WotLK?', 'Kirin Tor Signet', 5, 'medium', 'Items'),
	(167, 'Which rare fishing item grants underwater breathing and increased swimming speed?', 'Aquatic Agility Wand', 4, 'medium', 'Items'),
	(168, 'Which item is required to summon Nightbane in the Karazhan raid?', 'Blackened Urn', 8, 'hard', 'Items'),
	(169, 'What is the name of the legendary sword wielded by the Lich King?', 'Frostmourne', 10, 'hard', 'Items'),
	(170, 'Which consumable item is used to gain a temporary buff when turning in Zul\'Gurub coins?', 'Zanza\'s Potions', 5, 'medium', 'Items'),
	(171, 'Which item drops from Baron Rivendare in Stratholme and has a chance to give a mount?', 'Deathcharger\'s Reins', 7, 'medium', 'Items'),
	(172, 'What is the name of the item dropped from Kael\'thas in Tempest Keep that starts the Al\'ar mount quest?', 'Ashes of Al\'ar', 8, 'hard', 'Items'),
	(173, 'Which epic melee weapon drops from Zul\'Gurub and resembles a tiger claw?', 'Arlokk\'s Grasp', 6, 'medium', 'Items'),
	(174, 'What is the name of the key needed to access Shattered Halls in Hellfire Citadel?', 'Shattered Halls Key', 5, 'medium', 'Items'),
	(175, 'Which item from Naxxramas is a highly sought-after caster weapon that drops from Kel\'Thuzad?', 'Staff of the Plaguehound', 8, 'hard', 'Items'),
	(176, 'Which quest requires you to deliver a message to King Varian Wrynn in Stormwind?', 'A Call to Arms', 3, 'easy', 'Quests'),
	(177, 'What item is used to set your home location in World of Warcraft?', 'Hearthstone', 2, 'easy', 'Items'),
	(178, 'Which quest in the Barrens involves retrieving Kodo hides?', 'Kodo Roundup', 2, 'easy', 'Quests'),
	(179, 'Which quest chain in Elwynn Forest has you dealing with the Defias Brotherhood?', 'The Defias Brotherhood', 3, 'easy', 'Quests'),
	(180, 'Which quest chain in the Eastern Plaguelands involves helping the ghost of a little girl?', 'Little Pamela', 5, 'medium', 'Quests'),
	(183, 'What is the name of the item needed to complete the quest "The Missing Diplomat"?', 'SI:7 Badge', 3, 'easy', 'Items'),
	(184, 'Which consumable item restores health over time and is crafted by cooks?', 'Spiced Wolf Meat', 2, 'easy', 'Items'),
	(185, 'What is the name of the item that allows you to resurrect players in battle?', 'Ankh', 3, 'easy', 'Items'),
	(186, 'Which class-specific ability summons a spectral steed for Paladins?', 'Summon Charger', 8, 'hard', 'Class'),
	(187, 'Which class can learn the ability "Rain of Fire"?', 'Warlock', 6, 'medium', 'Class'),
	(188, 'What ability is unlocked by Druids at level 68 that allows them to instantly shift into flight form?', 'Swift Flight Form', 9, 'hard', 'Class'),
	(189, 'Which hidden city within Stranglethorn Vale served as a sanctuary for pirates?', 'Booty Bay', 5, 'medium', 'City'),
	(190, 'What is the name of the secretive underground goblin city located beneath Kezan?', 'Undermine', 9, 'hard', 'City'),
	(191, 'Which city houses the headquarters of the secretive SI:7 organization?', 'Stormwind', 4, 'medium', 'City'),
	(192, 'What in-game holiday involves fighting the Headless Horseman?', 'Hallow\'s End', 3, 'easy', 'Event'),
	(193, 'Which event marks the summoning of Lord Ahune in the Slave Pens during midsummer?', 'Midsummer Fire Festival', 3, 'easy', 'Event'),
	(194, 'Which annual event allows players to drink Dark Iron Dwarves under the table?', 'Brewfest', 4, 'easy', 'Event'),
	(195, 'Which troll tribe is native to the Ghostlands and Zul\'Aman?', 'Amani', 9, 'hard', 'Race'),
	(196, 'Which race in TBC is known for being able to speak to the Naaru?', 'Draenei', 8, 'hard', 'Race'),
	(197, 'What race was introduced in WotLK as a faction tied to Northrend?', 'Taunka', 9, 'hard', 'Race'),
	(198, 'Which zone in Kalimdor contains the ruined city of Eldre\'Thalas?', 'Feralas', 9, 'hard', 'Zone'),
	(199, 'Which zone in Outland is home to the Aldor and Scryer factions in Shattrath City?', 'Terokkar Forest', 8, 'hard', 'Zone'),
	(200, 'Which zone features the Scourge citadel known as Naxxramas in WotLK?', 'Dragonblight', 9, 'hard', 'Zone'),
	(201, 'Who led the ancient kaldorei forces during the War of the Ancients?', 'Malfurion Stormrage', 9, 'hard', 'Lore'),
	(202, 'Which Titan keeper was tasked with overseeing the creation of Ulduar\'s defenses?', 'Loken', 8, 'hard', 'Lore'),
	(203, 'Which artifact did Ner\'zhul use to tear open dimensional rifts and destroy Draenor?', 'The Skull of Gul\'dan', 10, 'hard', 'Lore'),
	(204, 'Which weapon is required to summon Thunderaan the Windseeker?', 'Sulfuron Hammer', 8, 'hard', 'Lore'),
	(205, 'Which item obtained in Icecrown Citadel helps form Shadowmourne?', 'Shadowfrost Shard', 10, 'hard', 'Items'),
	(206, 'Which trinket in WotLK enhances healing and drops from Ulduar bosses?', 'Solace of the Fallen', 9, 'hard', 'Items'),
	(207, 'Which dungeon in Kalimdor features a temple devoted to the Avatar of Hakkar?', 'Sunken Temple', 7, 'medium', 'Dungeon'),
	(208, 'Which dungeon in Zangarmarsh serves as a base for the naga in Outland?', 'The Slave Pens', 6, 'medium', 'Dungeon'),
	(209, 'Which dungeon in WotLK includes an encounter with the vrykul king Ymiron?', 'Utgarde Pinnacle', 5, 'medium', 'Dungeon'),
	(210, 'Which raid instance contains the demon lord Kil\'jaeden?', 'Sunwell Plateau', 8, 'hard', 'Raid'),
	(211, 'Which raid in Kalimdor is associated with the corrupt Emerald Nightmare?', 'The Temple of Ahn\'Qiraj', 7, 'medium', 'Lore'),
	(212, 'Which Old God is encountered in the depths of Ulduar?', 'Yogg-Saron', 9, 'hard', 'Raid'),
	(213, 'Which quest chain in Outland leads to the battle against Illidan?', 'The Black Temple Attunement', 9, 'hard', 'Quests'),
	(214, 'Which quest involves slaying elite ogres in Dire Maul to secure Eldre\'Thalas?', 'The Gordok Ogre Suit', 6, 'medium', 'Quests'),
	(215, 'What is the name of the quest chain in WotLK involving the Argent Tournament?', 'The Champion\'s Call', 7, 'medium', 'Quests'),
	(216, 'Which faction was formed by remnants of the Scarlet Crusade?', 'Scarlet Onslaught', 7, 'medium', 'Faction'),
	(217, 'Which faction in Outland is responsible for the protection of nature and the defense of Zangarmarsh?', 'Cenarion Expedition', 6, 'medium', 'Faction'),
	(218, 'Which faction in WotLK opposes the Blue Dragonflight\'s ambitions?', 'The Wyrmrest Accord', 7, 'medium', 'Faction'),
	(219, 'Which zone in Outland contains the shattered remnants of Draenor?', 'Netherstorm', 7, 'medium', 'Zone'),
	(220, 'Which zone in the Eastern Kingdoms is home to the Sunwell Plateau raid?', 'Isle of Quel\'Danas', 8, 'medium', 'Zone'),
	(221, 'Which zone in Northrend is known for the presence of the Grizzly Hills furbolgs?', 'Grizzly Hills', 7, 'medium', 'Zone'),
	(222, 'Which zone is home to the towering mountain known as Blackrock Mountain?', 'Burning Steppes', 9, 'hard', 'Zone'),
	(223, 'Which zone in Kalimdor is home to the Timbermaw Hold and Furbolgs?', 'Felwood', 9, 'hard', 'Zone'),
	(224, 'Which zone in Outland features the Temple of Telhamat and the Pools of Aggonar?', 'Hellfire Peninsula', 8, 'medium', 'Zone'),
	(225, 'Which raid is home to the final boss Onyxia?', 'Onyxia\'s Lair', 3, 'easy', 'Raid'),
	(226, 'Which raid is located within Blackrock Mountain and features Nefarian?', 'Blackwing Lair', 4, 'easy', 'Raid'),
	(227, 'Which raid in Outland features Magtheridon as its final boss?', 'Magtheridon\'s Lair', 3, 'easy', 'Raid'),
	(228, 'Which Northrend raid involves the Argent Crusade\'s battle against the Scourge?', 'Trial of the Crusader', 4, 'medium', 'Raid'),
	(229, 'Which raid in Vanilla WoW is home to Ragnaros, the Firelord?', 'Molten Core', 3, 'easy', 'Raid'),
	(230, 'Which race introduced in The Burning Crusade is known for its connection to the Naaru?', 'Draenei', 7, 'medium', 'Race'),
	(231, 'Which race was originally enslaved by trolls before establishing their empire in Stranglethorn Vale?', 'Gurubashi Trolls', 8, 'medium', 'Race'),
	(232, 'Which race is known for their racial ability "Gift of the Naaru"?', 'Draenei', 7, 'medium', 'Race'),
	(233, 'Which race of trolls allied with the Horde during the Third War?', 'Darkspear Trolls', 8, 'hard', 'Race'),
	(234, 'Which extinct race created the Well of Eternity?', 'Highborne', 9, 'hard', 'Race'),
	(235, 'Which race of giants is found guarding Titan constructs in Northrend?', 'Storm Giants', 8, 'hard', 'Race'),
	(236, 'Which item is required to teleport to Moonglade as a Druid?', 'Teleport: Moonglade', 2, 'easy', 'Items'),
	(238, 'What is the name of the hearthstone replacement item that teleports players to Dalaran?', 'Dalaran Hearthstone', 2, 'easy', 'Items'),
	(239, 'Which fish-based consumable restores health over time?', 'Spotted Yellowtail', 3, 'easy', 'Items'),
	(240, 'What ability is used by Paladins to summon their Charger mount?', 'Summon Charger', 3, 'easy', 'Items'),
	(241, 'Which faction, based in Wyrmrest Temple, is allied with the dragons?', 'The Wyrmrest Accord', 8, 'hard', 'Faction'),
	(243, 'Which faction leads the charge against the Scourge in the Argent Tournament during WotLK?', 'The Argent Crusade', 8, 'hard', 'Faction'),
	(244, 'Which Outland faction opposes the Naga presence in Zangarmarsh?', 'Cenarion Expedition', 9, 'hard', 'Faction'),
	(245, 'Which faction originally discovered the Titan facility Ulduar?', 'Explorers\' League', 9, 'hard', 'Faction'),
	(246, 'Which event occurs during December and features gift-giving?', 'Feast of Winter Veil', 3, 'easy', 'Event'),
	(247, 'Which event celebrates the harvest season and thanks the Earthmother?', 'Harvest Festival', 3, 'easy', 'Event'),
	(248, 'Which event occurs annually and involves collecting love tokens?', 'Love is in the Air', 3, 'easy', 'Event'),
	(249, 'Which annual event features fireworks and is celebrated in Booty Bay?', 'New Year\'s Eve', 4, 'medium', 'Event'),
	(250, 'Which world event involves honoring fallen heroes with bonfires and blessings?', 'Midsummer Fire Festival', 5, 'medium', 'Event'),
	(252, 'Which event marks the reopening of the Dark Portal in Outland?', 'The Dark Portal Opens', 7, 'hard', 'Event'),
	(253, 'Which event requires players to defeat world bosses tied to the Burning Legion?', 'Legion Invasion', 8, 'hard', 'Event'),
	(254, 'Which event in Silithus led to the opening of the Gates of Ahn\'Qiraj?', 'The Shifting Sands', 8, 'hard', 'Event'),
	(255, 'Which dungeon in Stranglethorn Vale features the Bloodsail Buccaneers and troll bosses?', 'Zul\'Gurub', 3, 'easy', 'Dungeon'),
	(256, 'Which dungeon in Blackrock Mountain is home to the boss known as Emperor Dagran Thaurissan?', 'Blackrock Depths', 4, 'easy', 'Dungeon'),
	(257, 'Which dungeon in WotLK is the entrance to Icecrown Citadel?', 'The Forge of Souls', 4, 'medium', 'Dungeon'),
	(258, 'Which dungeon in Kalimdor features the boss known as the Avatar of Hakkar?', 'Sunken Temple', 9, 'hard', 'Dungeon'),
	(259, 'Which Outland dungeon, located in Zangarmarsh, features Quagmirran as the final boss?', 'The Slave Pens', 9, 'hard', 'Dungeon'),
	(260, 'Which dungeon in Northrend is home to the Lich King\'s vrykul minions?', 'Utgarde Keep', 4, 'medium', 'Dungeon'),
	(261, 'Which Druid form is used for healing?', 'Tree of Life', 6, 'medium', 'Class'),
	(262, 'Which Paladin ability damages nearby undead and demons?', 'Holy Wrath', 9, 'hard', 'Class'),
	(263, 'Which ability allows Shamans to reincarnate after death?', 'Reincarnation', 6, 'medium', 'Class'),
	(264, 'Which Warlock ability temporarily enslaves powerful demons as minions?', 'Enslave Demon', 9, 'hard', 'Class'),
	(265, 'Which class ability allows Rogues to detect traps and hidden enemies?', 'Detect Traps', 8, 'hard', 'Class'),
	(266, 'Which city in Kalimdor is known as the night elf capital?', 'Darnassus', 6, 'medium', 'City'),
	(267, 'Which city in Borean Tundra serves as the main Alliance hub in Northrend?', 'Valiance Keep', 6, 'medium', 'City'),
	(268, 'Which city in Outland features the Aldor Rise and Scryer Tier?', 'Shattrath City', 6, 'medium', 'City'),
	(269, 'Which city in WotLK is located in the Howling Fjord and serves the Forsaken?', 'Vengeance Landing', 8, 'hard', 'City'),
	(270, 'Which underground city in Lordaeron serves as the Forsaken\'s capital?', 'Undercity', 5, 'medium', 'City'),
	(272, 'Which zone in Northrend contains the Nexus and the Eye of Eternity raid?', 'Borean Tundra', 6, 'medium', 'Zone'),
	(273, 'Which troll-infested island in Stranglethorn Vale is home to Zul\'Gurub?', 'Zul\'Gurub', 6, 'medium', 'Zone'),
	(275, 'Which class places totems to provide buffs and utility effects?', 'Shaman', 4, 'easy', 'Class'),
	(276, 'Which class uses the ability "Army of the Dead" to summon undead minions?', 'Death Knight', 7, 'medium', 'Class'),
	(277, 'Which powerful demon betrayed Prince Kael\'thas and manipulated him during The Burning Crusade?', 'Kil\'jaeden', 8, 'hard', 'Lore'),
	(278, 'Who originally led the Argent Crusade before Highlord Tirion Fordring?', 'Alexandros Mograine', 7, 'medium', 'Lore'),
	(279, 'Which dungeon in WotLK features the boss King Ymiron?', 'Utgarde Pinnacle', 5, 'medium', 'Dungeon'),
	(280, 'What is the final raid of The Burning Crusade expansion?', 'Sunwell Plateau', 7, 'hard', 'Raid'),
	(281, 'Which faction in Outland is primarily composed of draenei exiles?', 'The Aldor', 6, 'medium', 'Faction'),
	(282, 'Which dragonflight opposes Malygos and works with the Wyrmrest Accord in WotLK?', 'The Red Dragonflight', 7, 'medium', 'Faction'),
	(283, 'Which annual event involves sampling exotic brews and competing in drinking contests?', 'Brewfest', 4, 'easy', 'Event'),
	(284, 'Which holiday event in World of Warcraft involves giving and receiving gifts under a tree?', 'Feast of Winter Veil', 3, 'easy', 'Event'),
	(285, 'Which item is used to access the Eye of Eternity and summon Malygos in WotLK?', 'Key to the Focusing Iris', 8, 'hard', 'Items'),
	(286, 'Which item drops from the Lich King in Icecrown Citadel and is used for crafting Shadowmourne?', 'Shadowfrost Shard', 9, 'hard', 'Items'),
	(287, 'Which zone in the Eastern Kingdoms is home to the Scarlet Monastery?', 'Tirisfal Glades', 3, 'easy', 'Zone'),
	(288, 'Which Outland zone is known for its floating islands and mana storms?', 'Netherstorm', 6, 'medium', 'Zone'),
	(289, 'Which snowy zone in Northrend is home to the Grizzly Hills furbolgs?', 'Grizzly Hills', 5, 'medium', 'Zone'),
	(291, 'Which jungle zone in Azeroth features the infamous Gurubashi Arena?', 'Stranglethorn Vale', 5, 'medium', 'Zone'),
	(292, 'Which zone is the starting area for the Draenei in The Burning Crusade?', 'Azuremyst Isle', 3, 'easy', 'Zone'),
	(293, 'Which zone in Kalimdor is known for its large Silithid hives?', 'Silithus', 6, 'medium', 'Zone'),
	(294, 'Which zone in Outland features the Cenarion Thicket and Auchindoun?', 'Terokkar Forest', 5, 'medium', 'Zone'),
	(295, 'Which class uses the ability "Death Coil" to damage and fear enemies?', 'Warlock', 4, 'easy', 'Class'),
	(296, 'Which class has the ability to heal allies with "Holy Light"?', 'Paladin', 4, 'easy', 'Class'),
	(297, 'Which class uses "Steady Shot" as a core damage ability?', 'Hunter', 6, 'medium', 'Class'),
	(298, 'Which class has a unique resource called "Runic Power"?', 'Death Knight', 7, 'medium', 'Class'),
	(299, 'Which class can summon a Water Elemental as a pet?', 'Mage', 5, 'medium', 'Class'),
	(300, 'Which legendary sword wielded by Highlord Tirion Fordring played a key role against the Lich King?', 'Ashbringer', 6, 'medium', 'Lore'),
	(301, 'Which dragon aspect leads the Blue Dragonflight during WotLK?', 'Malygos', 5, 'medium', 'Lore'),
	(302, 'Which orc warlock betrayed the Horde by allying with Kil\'jaeden during the First War?', 'Gul\'dan', 7, 'hard', 'Lore'),
	(303, 'Which Night Elf leader played a key role in defeating Archimonde at the Battle of Mount Hyjal?', 'Malfurion Stormrage', 4, 'easy', 'Lore'),
	(304, 'Which WotLK raid includes the final boss encounter with Kel\'Thuzad?', 'Naxxramas', 6, 'medium', 'Raid'),
	(305, 'Which raid instance features the Old God C\'Thun as its final boss?', 'Ahn\'Qiraj', 6, 'medium', 'Raid'),
	(306, 'Which dungeon in Northrend is the entrance to Icecrown Citadel?', 'The Forge of Souls', 5, 'medium', 'Dungeon'),
	(307, 'Which boss in Blackrock Depths drops the key needed to access deeper areas of the dungeon?', 'High Interrogator Gerstahn', 6, 'medium', 'Dungeon'),
	(308, 'Which faction leads the fight against the Scourge in Northrend during WotLK?', 'The Argent Crusade', 5, 'medium', 'Faction'),
	(309, 'Which faction of night elves is dedicated to preserving nature and balance?', 'Cenarion Circle', 6, 'medium', 'Faction'),
	(310, 'Which faction, led by Akama, opposes the Burning Legion during The Burning Crusade?', 'Ashtongue Deathsworn', 7, 'hard', 'Faction'),
	(311, 'Which world event involves killing the Headless Horseman?', 'Hallow\'s End', 3, 'easy', 'Event'),
	(312, 'Which holiday event involves hunting eggs during the spring?', 'Noblegarden', 4, 'easy', 'Event'),
	(313, 'Which legendary item from Molten Core is needed to summon Ragnaros?', 'Aqual Quintessence', 6, 'medium', 'Items'),
	(314, 'Which weapon dropped from Illidan in Black Temple is part of the Warglaives of Azzinoth set?', 'Main-Hand Warglaive of Azzinoth', 7, 'hard', 'Items'),
	(315, 'What is the name of the island where Blood Elves start their journey in The Burning Crusade?', 'Sunstrider Isle', 2, 'easy', 'Zone'),
	(316, 'Which class is able to summon a Felhunter as a combat pet?', 'Warlock', 2, 'easy', 'Class'),
	(317, 'What is the name of the large desert zone in Kalimdor home to many Silithid?', 'Silithus', 3, 'easy', 'Zone'),
	(319, 'Which dragon serves as the final boss of Onyxia\'s Lair?', 'Onyxia', 3, 'easy', 'Raid'),
	(320, 'What is the name of the elite centaur faction that inhabits Desolace?', 'Gelkis Clan Centaur', 5, 'medium', 'Faction'),
	(321, 'Which dungeon in Dalaran features an encounter with the dragon Cyanigosa?', 'The Violet Hold', 5, 'medium', 'Dungeon'),
	(322, 'What is the name of the elemental plane accessed through the Molten Core raid?', 'The Elemental Plane of Fire', 6, 'medium', 'Raid'),
	(323, 'Which quest chain in Zangarmarsh requires players to defeat the giant bog lord, Boglash?', 'Leader of the Darkcrest', 5, 'medium', 'Quests'),
	(324, 'Which snowy Northrend zone is home to the Vrykul and the settlement of Valgarde?', 'Howling Fjord', 5, 'medium', 'Zone'),
	(325, 'Which stronghold in the Alterac Mountains is controlled by ogres?', 'Alterac Keep', 6, 'medium', 'Zone'),
	(326, 'Which Outland daily quest hub is associated with gaining reputation with the Netherwing Dragonflight?', 'Netherwing Ledge', 5, 'medium', 'Quests'),
	(328, 'Which class places an Earthbind Totem to slow enemies in its area of effect?', 'Shaman', 4, 'easy', 'Class'),
	(329, 'Which Outland zone is characterized by its arcane storms and floating islands?', 'Netherstorm', 5, 'medium', 'Zone'),
	(330, 'What is the name of the Orc warrior who challenged Thrall to a Mak\'gora in Nagrand?', 'Garrosh Hellscream', 8, 'hard', 'Lore'),
	(331, 'Which Old God corrupted Deathwing and played a major role in the War of the Ancients?', 'N\'Zoth', 9, 'hard', 'Lore'),
	(332, 'What is the name of the demonic volcano in Shadowmoon Valley used by the Burning Legion?', 'The Hand of Gul\'dan', 8, 'hard', 'Zone'),
	(333, 'Which Titan complex in Northrend contains Yogg-Saron?', 'Ulduar', 9, 'hard', 'Zone'),
	(334, 'Which artifact, linked to the Light, is sought by the Scourge and the Argent Crusade during WotLK?', 'The Ashbringer', 9, 'hard', 'Lore'),
	(335, 'What is the name of the legendary warlock who created the original Council of Tirisfal?', 'Alodi', 9, 'hard', 'Lore'),
	(336, 'In The Burning Crusade, which demon hunter guards the entrance to Black Temple?', 'Supremus', 8, 'hard', 'Raid'),
	(337, 'Which ethereal boss is encountered in Mana-Tombs and is associated with the void lord in Auchindoun?', 'Nexus-Prince Shaffar', 9, 'hard', 'Dungeon'),
	(338, 'Which location in Azshara is known for being an ancient Highborne ruin?', 'The Ruins of Eldarath', 8, 'hard', 'Zone'),
	(339, 'What is the name of the corrupted World Tree located in the northern region of Felwood?', 'Vordrassil', 8, 'hard', 'Zone'),
	(340, 'Which event, driven by Arthas\'s betrayal, led to the creation of the Undercity beneath Lordaeron?', 'The Fall of Lordaeron', 8, 'hard', 'Event'),
	(341, 'Which dragonspawn leads the defense of the Ruby Sanctum during WotLK?', 'Halion', 9, 'hard', 'Raid'),
	(342, 'Which Northrend zone was named after the troll warlord who fought the Scourge?', 'Zul\'Drak', 9, 'hard', 'Zone'),
	(343, 'Which item is required to defeat Malygos in the Eye of Eternity raid?', 'Key to the Focusing Iris', 8, 'hard', 'Items'),
	(344, 'Which elite druidic faction is responsible for combating the corruption of the Emerald Nightmare?', 'Guardians of Hyjal', 9, 'hard', 'Faction'),
	(345, 'What is the name of the powerful demon imprisoned within the Sunwell Plateau raid?', 'Kil\'jaeden', 9, 'hard', 'Raid'),
	(346, 'Which Titan relic is the centerpiece of the Halls of Stone dungeon in Northrend?', 'The Tribunal of Ages', 9, 'hard', 'Lore'),
	(347, 'What was the name of the Draenei ship that crashed on Azuremyst Isle?', 'The Exodar', 6, 'medium', 'Lore'),
	(348, 'Which Naaru was corrupted and used by the Blood Elves in Sunwell Plateau?', 'M\'uru', 9, 'hard', 'Lore'),
	(349, 'Which Scarlet Crusade leader was involved during the fall of Tyr\'s Hand?', 'Highlord Taelan Fordring', 9, 'hard', 'Lore'),
	(350, 'Which faction does the renowned explorer Brann Bronzebeard belong to?', 'Explorers\' League', 6, 'medium', 'Faction'),
	(351, 'Which elite group of night elves was tasked with guarding the Barrow Deeps during the War of the Ancients?', 'Wardens', 8, 'hard', 'Lore'),
	(352, 'What is the name of the powerful necromancer who founded the Cult of the Damned?', 'Kel\'Thuzad', 8, 'medium', 'Lore'),
	(353, 'Which rare mount in WotLK is obtained from the Time-Lost Proto-Drake in Storm Peaks?', 'Time-Lost Proto-Drake', 9, 'hard', 'Mounts'),
	(355, 'Which dungeon in Storm Peaks takes place inside a massive Titan facility?', 'Halls of Lightning', 6, 'medium', 'Dungeon'),
	(356, 'What is the name of the legendary staff obtained in Ahn\'Qiraj?', 'Atiesh, Greatstaff of the Guardian', 10, 'hard', 'Items'),
	(357, 'Which ancient Kaldorei general defected from Queen Azshara and aided in defeating the Burning Legion?', 'Jarod Shadowsong', 9, 'hard', 'Lore'),
	(358, 'Which item allows players to access the hidden entrance to the Karazhan crypt?', 'Skeleton Key', 7, 'medium', 'Items'),
	(359, 'Which faction, composed primarily of shaman, opposes the Twilight\'s Hammer?', 'Earthen Ring', 6, 'medium', 'Faction'),
	(360, 'Which questline in WotLK focuses on helping a blue dragon reunite with their mate in Coldarra?', 'Coldarra Reunion', 8, 'medium', 'Quests'),
	(361, 'What is the name of the ruling council of eredar leaders who serve Kil\'jaeden and Archimonde?', 'The Triumvirate', 9, 'hard', 'Lore'),
	(362, 'Which type of node is needed for mining khorium ore in Outland?', 'Khorium Vein', 7, 'medium', 'Professions'),
	(363, 'Which ancient troll city was corrupted and overrun by the Blood God Hakkar?', 'Zul\'Gurub', 6, 'medium', 'Zone'),
	(364, 'Which dungeon in Blackrock Mountain features the fire elemental Pyroguard Emberseer?', 'Blackrock Spire', 6, 'medium', 'Dungeon'),
	(365, 'What is the name of the powerful demon imprisoned beneath the Well of Eternity?', 'Mannoroth', 9, 'hard', 'Lore'),
	(366, 'What type of enemies does the Blood Elf racial ability "Arcane Torrent" silence within its radius?', 'All enemy spellcasters', 8, 'medium', 'Race'),
	(367, 'Which hunter pet family is known for having the "Prowl" ability to stealth?', 'Cats', 7, 'medium', 'Class'),
	(368, 'Which cursed runeblade was wielded by Arthas before he became the Lich King?', 'Frostmourne', 10, 'hard', 'Items'),
	(369, 'Which rare pet is dropped by the Captured Firefly in Zangarmarsh?', 'Captured Firefly', 8, 'medium', 'Pets'),
	(370, 'Which orc warlock corrupted the original Horde by introducing them to fel magic?', 'Gul\'dan', 8, 'hard', 'Lore'),
	(371, 'Which daily quest hub in WotLK is located in Grizzly Hills and involves fighting trolls?', 'Zim\'Torga', 7, 'medium', 'Quests'),
	(372, 'Which faction, based in Silithus, fights to protect Azeroth\'s natural balance?', 'Cenarion Circle', 6, 'medium', 'Faction'),
	(373, 'Who is the final boss of the Magisters\' Terrace dungeon in The Burning Crusade?', 'Kael\'thas Sunstrider', 7, 'medium', 'Dungeon'),
	(374, 'Which item is required to summon the Lurker Below in Serpentshrine Cavern?', 'Fishing Pole', 4, 'easy', 'Items'),
	(375, 'Which goblin cartels are found in Booty Bay and Ratchet?', 'Steamwheedle Cartel', 6, 'medium', 'Faction'),
	(376, 'Which world boss, known for terrorizing adventurers, patrols near Stratholme?', 'Lord Kazzak', 9, 'hard', 'Boss'),
	(377, 'Which orc blacksmith is credited with forging the legendary Doomhammer?', 'Orgrim Doomhammer', 8, 'medium', 'Lore'),
	(378, 'Which troll loa, known as the Blood God, is the final boss in Zul\'Gurub?', 'Hakkar the Soulflayer', 9, 'hard', 'Lore'),
	(379, 'Which wolf-like creatures in Felwood drop the Salve of Immolation?', 'Felpaw Wolves', 7, 'medium', 'Zone'),
	(380, 'What is the name of the elite dragon found in the Borean Tundra during WotLK?', 'Saragosa', 8, 'medium', 'Boss'),
	(381, 'Which legendary mace is obtained from Icecrown Citadel in WotLK?', 'Shadowmourne', 10, 'hard', 'Items'),
	(382, 'Which large world tree grew on the roots of the original Nordrassil?', 'Teldrassil', 7, 'medium', 'Lore'),
	(383, 'Who betrayed Illidan and led to his downfall at the Black Temple?', 'Akama', 8, 'medium', 'Lore'),
	(384, 'Which final boss of the Dragon Soul raid is responsible for dropping its most significant loot?', 'Deathwing', 10, 'hard', 'Boss'),
	(385, 'Which Titan complex in Northrend was built to imprison Yogg-Saron?', 'Ulduar', 7, 'medium', 'Lore'),
	(386, 'Which WotLK daily questline involves jousting with other champions?', 'The Argent Tournament', 7, 'medium', 'Quests'),
	(387, 'Which faction based in Shattrath City opposes the Burning Legion during The Burning Crusade?', 'Sha\'tar', 6, 'medium', 'Faction'),
	(388, 'Which rare undead mount can be obtained from Baron Rivendare in Stratholme?', 'Deathcharger\'s Reins', 9, 'hard', 'Mounts'),
	(389, 'Which annual in-game event celebrates the anniversary of World of Warcraft\'s release?', 'WoW Anniversary Event', 5, 'medium', 'Event'),
	(390, 'Which paladin was the first to hold the title of Highlord of the Silver Hand?', 'Uther the Lightbringer', 8, 'medium', 'Lore'),
	(391, 'Which alchemy-crafted consumable grants underwater breathing and increased swim speed?', 'Elixir of Water Breathing', 7, 'medium', 'Items'),
	(392, 'Which raptor in Un\'Goro Crater can drop a rare green mount?', 'Ravasaur Matriarch', 8, 'medium', 'Boss'),
	(393, 'What is the name of the titan keeper who serves as the main antagonist in Halls of Lightning?', 'Loken', 8, 'medium', 'Boss'),
	(394, 'Which rare trinket is dropped from Princess Huhuran in Ahn\'Qiraj?', 'Talisman of Ephemeral Power', 8, 'medium', 'Items'),
	(395, 'Which faction in Zangarmarsh opposes Lady Vashj\'s forces?', 'Cenarion Expedition', 6, 'medium', 'Faction'),
	(396, 'Which druid-specific questline begins in Cenarion Refuge and rewards Swift Flight Form?', 'Swift Flight Form', 7, 'medium', 'Quests'),
	(397, 'Who was responsible for unleashing the Plague of Undeath across Lordaeron?', 'Kel\'Thuzad', 8, 'medium', 'Lore'),
	(398, 'Which weekly fishing event takes place in Stranglethorn Vale and offers rare rewards?', 'Stranglethorn Fishing Extravaganza', 6, 'medium', 'Event'),
	(399, 'Which boss in Upper Blackrock Spire drops the Seal of Ascension?', 'Warchief Rend Blackhand', 7, 'medium', 'Dungeon'),
	(400, 'Which WotLK boss drops the reins of the Blue Proto-Drake?', 'Skadi the Ruthless', 8, 'medium', 'Mounts'),
	(401, 'Which profession enables players to craft gems that can be socketed into gear?', 'Jewelcrafting', 3, 'easy', 'Professions'),
	(402, 'Which rare herb, highly sought after in Classic WoW, is considered the pinnacle of herbalism?', 'Black Lotus', 4, 'easy', 'Professions'),
	(403, 'Which rare ore is often found alongside Adamantite veins in Outland?', 'Eternium', 6, 'medium', 'Professions'),
	(404, 'Which profession allows players to cook meals that provide buffs?', 'Cooking', 2, 'easy', 'Professions'),
	(405, 'Which rare fish, found in Azshara and other locations, is used in alchemy to craft unique potions?', 'Deviate Fish', 6, 'medium', 'Professions'),
	(406, 'Which leatherworking specialization focuses on crafting leather armor for Rogues and Druids?', 'Tribal Leatherworking', 6, 'medium', 'Professions'),
	(407, 'Which Classic WoW material is used to craft Mooncloth for Tailoring?', 'Felcloth', 7, 'medium', 'Professions'),
	(408, 'Which profession enables players to craft flasks, potions, and elixirs?', 'Alchemy', 3, 'easy', 'Professions'),
	(409, 'Which engineering item temporarily grants invisibility to players?', 'Gnomish Cloaking Device', 7, 'medium', 'Professions'),
	(410, 'Which herbalism node in Zangarmarsh is essential for high-level potions in TBC?', 'Dreaming Glory', 6, 'medium', 'Professions'),
	(411, 'Which rare Outland ore is smelted into Khorium Bars?', 'Khorium Ore', 7, 'medium', 'Professions'),
	(412, 'Which Tailoring cloth is used for making Ebonweave armor?', 'Spellweave', 8, 'hard', 'Professions'),
	(413, 'Which item crafted by Blacksmithing is used to summon bosses in Molten Core?', 'Aqual Quintessence', 9, 'hard', 'Professions'),
	(414, 'Which rare fish must be caught to complete Nat Pagle\'s fishing quest?', 'Feralas Ahi', 7, 'medium', 'Professions'),
	(415, 'Which material is essential for crafting Thunderfury, Blessed Blade of the Windseeker?', 'Arcanite Bar', 9, 'hard', 'Professions'),
	(416, 'Which ore, abundant in Northrend, is used to craft Titansteel?', 'Saronite', 6, 'medium', 'Professions'),
	(417, 'Which secondary profession allows players to collect fossils and relics?', 'Archaeology', 5, 'medium', 'Professions'),
	(418, 'Which engineering item allows players to teleport directly to Gadgetzan?', 'Ultrasafe Transporter: Gadgetzan', 8, 'hard', 'Professions'),
	(419, 'Which cooking ingredient is gathered from Clefthoofs in Nagrand?', 'Clefthoof Meat', 5, 'medium', 'Professions'),
	(420, 'Which weapon enchant applies fire damage on hit?', 'Fiery Weapon', 8, 'hard', 'Professions'),
	(421, 'Which rare tailoring item in TBC is needed to craft epic Shadoweave armor?', 'Primal Shadow', 7, 'medium', 'Professions'),
	(422, 'Which high-level herbalism node in Icecrown is often protected by elite mobs?', 'Icethorn', 8, 'hard', 'Professions'),
	(423, 'Which alchemy potion in Classic WoW grants underwater breathing?', 'Elixir of Water Breathing', 4, 'easy', 'Professions'),
	(424, 'Which rare ore from Ulduar is crucial for high-level engineering in WotLK?', 'Titanium Ore', 6, 'medium', 'Professions'),
	(425, 'Which leatherworking specialization focuses on crafting armor kits and gear for tanking classes?', 'Elemental Leatherworking', 6, 'medium', 'Professions'),
	(426, 'Which gem, crafted by Jewelcrafters in WotLK, increases spell power?', 'Runed Cardinal Ruby', 7, 'medium', 'Professions'),
	(427, 'Which tailoring material is crafted using Netherweave Cloth in TBC?', 'Bolt of Netherweave', 4, 'easy', 'Professions'),
	(428, 'Which rare fish is the main ingredient in the recipe for Savory Deviate Delight?', 'Deviate Fish', 6, 'medium', 'Professions'),
	(429, 'Which unique engineering mount is only obtainable through the profession in WotLK?', 'Mekgineer\'s Chopper', 8, 'hard', 'Professions'),
	(430, 'Which cooking recipe is obtained during Brewfest and grants a stamina buff?', 'Spicy Smoked Sausage', 5, 'medium', 'Professions'),
	(431, 'Which rare pet, a blue whelp, can drop from mobs in Winterspring?', 'Azure Whelpling', 8, 'hard', 'Pets'),
	(432, 'Which pet, a turtle, is one of the rewards from the Children\'s Week questline?', 'Speedy', 6, 'medium', 'Pets'),
	(433, 'Which pet is obtained from the Winter Veil event and resembles a mechanical gnome?', 'Clockwork Rocket Bot', 5, 'medium', 'Pets'),
	(435, 'Which battle pet is earned by completing the questline "A Shard of Frozen Tears"?', 'Frosty', 7, 'medium', 'Pets'),
	(436, 'Which companion pet is a reward for completing achievements during Brewfest?', 'Pint-Sized Pink Pachyderm', 6, 'medium', 'Pets'),
	(437, 'Which rare parrot companion can be obtained from the Zul\'Gurub raid?', 'Hyacinth Macaw', 9, 'hard', 'Pets'),
	(438, 'Which pet can be purchased from the Netherwing faction after gaining reputation?', 'Nether Ray Fry', 8, 'hard', 'Pets'),
	(439, 'Which pet resembles a small version of the infernal demon from Black Temple?', 'Fiendish Imp', 8, 'hard', 'Pets'),
	(440, 'Which rare pet is caught by fishing in the sewers of Dalaran?', 'Giant Sewer Rat', 7, 'medium', 'Pets'),
	(441, 'Which engineering item summons a mechanical squirrel as a companion pet?', 'Mechanical Squirrel Box', 5, 'medium', 'Pets'),
	(442, 'Which snake companion pet is available from a vendor in Orgrimmar?', 'Black Kingsnake', 4, 'easy', 'Pets'),
	(443, 'Which pet was awarded during WoW\'s 5th Anniversary event?', 'Onyxian Whelpling', 9, 'hard', 'Pets'),
	(444, 'Which fiery pet resembling a molten core elemental is dropped by bosses in Molten Core?', 'Lava Crab', 8, 'hard', 'Pets'),
	(445, 'Which pet, resembling a snowman, is obtainable during the Winter Veil event?', 'Tiny Snowman', 6, 'medium', 'Pets'),
	(446, 'Which rare Wailing Caverns pet is dropped by Deviate Faerie Dragon?', 'Deviate Hatchling', 7, 'medium', 'Pets'),
	(447, 'Which rare aquatic pet can be caught by fishing in the Verdantis River in Feralas?', 'Toothy', 7, 'medium', 'Pets'),
	(448, 'What is the name of the miniature slime pet found in Felwood?', 'Disgusting Oozeling', 8, 'hard', 'Pets'),
	(449, 'Which rare pet is found in the Storm Peaks and resembles a small proto-drake?', 'Proto-Drake Whelp', 8, 'hard', 'Pets'),
	(450, 'Which murloc pet was a reward from one of the earliest BlizzCon promotions?', 'Murky', 9, 'hard', 'Pets'),
	(451, 'Which rabbit companion is available from the Noblegarden event?', 'Spring Rabbit', 4, 'easy', 'Pets'),
	(453, 'Which pet is known for giving a large breath weapon animation when interacted with?', 'Lil\' XT', 6, 'medium', 'Pets'),
	(454, 'Which mechanical companion pet is created using engineering in TBC?', 'Mechanical Yeti', 6, 'medium', 'Pets'),
	(455, 'Which rare underwater companion can be caught by fishing in the coastal waters of Stranglethorn Vale?', 'Tiny Blue Carp', 7, 'medium', 'Pets'),
	(456, 'Which pet is awarded for completing all PvP battleground achievements in WotLK?', 'Armored Murloc', 9, 'hard', 'Pets'),
	(457, 'Which rare pet resembles a small sporebat and is a drop from Sporeggar in Zangarmarsh?', 'Sporeling Sprout', 8, 'hard', 'Pets'),
	(458, 'Which dragonhawk companion can be purchased in Quel\'Danas after defeating Kael\'thas?', 'Phoenix Hatchling', 7, 'medium', 'Pets'),
	(460, 'Which tiny fire elemental pet is looted from Ahune during the Midsummer Fire Festival?', 'Frigid Frostling', 6, 'medium', 'Pets'),
	(461, 'Which rare mount drops from Anzu in the Sethekk Halls dungeon?', 'Reins of the Raven Lord', 9, 'hard', 'Mounts'),
	(462, 'Which engineering-crafted flying mount was introduced in The Burning Crusade?', 'Flying Machine', 6, 'medium', 'Mounts'),
	(463, 'Which mount is awarded for completing the Argent Tournament achievements in WotLK?', 'Argent Charger', 7, 'medium', 'Mounts'),
	(464, 'Which fiery horse mount drops from Attumen the Huntsman in Karazhan?', 'Fiery Warhorse', 8, 'hard', 'Mounts'),
	(465, 'What is the name of the Horde-specific PvP wolf mount?', 'Frostwolf Howler', 5, 'medium', 'Mounts'),
	(466, 'Which rare phoenix mount drops from the Al\'ar encounter in Tempest Keep?', 'Ashes of Al\'ar', 9, 'hard', 'Mounts'),
	(467, 'Which classic mount requires exalted reputation with the Wintersaber Trainers?', 'Winterspring Frostsaber', 7, 'medium', 'Mounts'),
	(468, 'What is the name of the skeletal mount available to Forsaken players in Classic WoW?', 'Purple Skeletal Warhorse', 4, 'easy', 'Mounts'),
	(469, 'Which unique mount, obtained during the Gates of Ahn\'Qiraj event, drops from the Silithid boss in Ahn\'Qiraj?', 'Black Qiraji Resonating Crystal', 10, 'hard', 'Mounts'),
	(470, 'Which rare tiger mount could be obtained by defeating High Priest Thekal in Zul\'Gurub?', 'Swift Zulian Tiger', 9, 'hard', 'Mounts'),
	(471, 'Which WotLK mount is awarded to players who complete the Glory of the Ulduar Raider?', 'Rusted Proto-Drake', 8, 'hard', 'Mounts'),
	(472, 'Which rare aquatic mount can be fished from Northrend\'s waters and resembles a giant turtle?', 'Sea Turtle', 8, 'hard', 'Mounts'),
	(473, 'Which mount is awarded to players after collecting 100 mounts in WotLK?', 'Blue Dragonhawk', 8, 'hard', 'Mounts'),
	(474, 'Which flying mount is earned after gaining exalted reputation with the Netherwing faction?', 'Netherwing Drake', 6, 'medium', 'Mounts'),
	(475, 'What is the Alliance counterpart to the Swift Brown Wolf PvP mount?', 'Stormpike Battle Charger', 5, 'medium', 'Mounts'),
	(476, 'Which bear mount could be obtained by completing a timed run in the Zul\'Aman raid?', 'Amani War Bear', 9, 'hard', 'Mounts'),
	(477, 'Which flying mount in WotLK is crafted by engineers and resembles a helicopter?', 'Mekgineer\'s Chopper', 8, 'hard', 'Mounts'),
	(478, 'Which dragonhawk mount is earned for completing the "Mountain o\' Mounts" achievement?', 'Red Dragonhawk', 9, 'hard', 'Mounts'),
	(479, 'Which mount resembling a drake is awarded during Onyxia\'s anniversary event?', 'Onyxian Drake', 7, 'medium', 'Mounts'),
	(480, 'Which mount is dropped by Rivendare in Stratholme?', 'Deathcharger\'s Reins', 8, 'medium', 'Mounts'),
	(481, 'Which drake mount drops from Malygos in the Eye of Eternity raid?', 'Azure Drake', 9, 'hard', 'Mounts'),
	(482, 'What mount is rewarded from the Mag\'har faction in Nagrand for Horde players?', 'Cobalt War Talbuk', 6, 'medium', 'Mounts'),
	(484, 'Which mount is rewarded to Horde players who reach exalted with the Darkspear Trolls?', 'Swift Orange Raptor', 4, 'easy', 'Mounts'),
	(485, 'Which rare drake mount can be obtained from Skadi the Ruthless in Utgarde Pinnacle?', 'Blue Proto-Drake', 8, 'medium', 'Mounts'),
	(486, 'Which drake mount drops from Sartharion if all three drakes are kept alive during the encounter?', 'Twilight Drake', 9, 'hard', 'Mounts'),
	(488, 'Which classic mount is a reward from the AQ War Effort event?', 'Black Qiraji Battle Tank', 10, 'hard', 'Mounts'),
	(489, 'Which mount in WotLK is obtained from the Sons of Hodir reputation vendor?', 'Ice Mammoth', 6, 'medium', 'Mounts'),
	(490, 'Which boss in Black Temple drops the off-hand Warglaive of Azzinoth?', 'Illidan Stormrage', 9, 'hard', 'Boss'),
	(491, 'Which boss from Karazhan is associated with the opera house encounter and appears in The Wizard of Oz event?', 'The Crone', 7, 'medium', 'Boss'),
	(492, 'Who is the final boss of the Cathedral wing in the Scarlet Monastery?', 'High Inquisitor Whitemane', 5, 'medium', 'Boss'),
	(493, 'Which boss in the Sunwell Plateau raid corrupts M\'uru before being summoned?', 'Kil\'jaeden', 9, 'hard', 'Boss'),
	(494, 'What is the name of the spider boss found in the Naxxramas Arachnid Quarter?', 'Maexxna', 6, 'medium', 'Boss'),
	(495, 'Which titan construct serves as the final boss of Halls of Lightning?', 'Loken', 8, 'medium', 'Boss'),
	(496, 'Which boss in the Eye of Eternity is fought using flying mounts in WotLK?', 'Malygos', 8, 'hard', 'Boss'),
	(497, 'Who is the final boss of the Blackrock Spire dungeon in Classic WoW?', 'Overlord Wyrmthalak', 6, 'medium', 'Boss'),
	(498, 'Which hydra boss can be summoned by fishing in the Serpentshrine Cavern?', 'The Lurker Below', 7, 'medium', 'Boss'),
	(499, 'Which undead dragon serves as a boss in Icecrown Citadel?', 'Sindragosa', 9, 'hard', 'Boss'),
	(500, 'Which necromancer is the final boss of Scholomance and frequently summons skeletons?', 'Darkmaster Gandling', 6, 'medium', 'Boss'),
	(501, 'What is the name of the elite dragon world boss that patrols Ashenvale?', 'Emeriss', 8, 'hard', 'Boss'),
	(502, 'Which boss in Zul\'Farrak requires players to fight waves of trolls before engaging him?', 'Chief Ukorz Sandscalp', 6, 'medium', 'Boss'),
	(503, 'Which dragon world boss in Classic WoW guards the entrance to the Emerald Dream?', 'Ysondre', 8, 'hard', 'Boss'),
	(504, 'Who is the leader of the troll forces in Zul\'Gurub?', 'Hakkar the Soulflayer', 9, 'hard', 'Boss'),
	(505, 'Which elemental boss is summoned during the Midsummer Fire Festival?', 'Lord Ahune', 7, 'medium', 'Boss'),
	(506, 'Which Ulduar raid boss is known as the "Keeper of the Forge"?', 'Ignis the Furnace Master', 7, 'medium', 'Boss'),
	(507, 'Which boss in Utgarde Keep summons Vrykul skeletons during the encounter?', 'Prince Keleseth', 6, 'medium', 'Boss'),
	(508, 'Which boss in the Nexus uses frost magic to defeat players?', 'Keristrasza', 6, 'medium', 'Boss'),
	(509, 'Which boss in the Culling of Stratholme dungeon is the final encounter?', 'Mal\'Ganis', 7, 'medium', 'Boss'),
	(510, 'Which boss in Blackwing Lair is the son of Deathwing?', 'Nefarian', 9, 'hard', 'Boss'),
	(511, 'Which encounter in the Temple of Ahn\'Qiraj features twin bosses that share health?', 'The Twin Emperors', 9, 'hard', 'Boss'),
	(512, 'Which Serpentshrine Cavern boss fights players while summoning waves of water elementals?', 'Morogrim Tidewalker', 8, 'hard', 'Boss'),
	(513, 'Who leads the Scarlet Crusade forces in the Cathedral wing of the Scarlet Monastery?', 'Scarlet Commander Mograine', 8, 'hard', 'Boss'),
	(514, 'Which boss in the Obsidian Sanctum can drop drake mounts such as the Twilight Drake?', 'Sartharion', 7, 'medium', 'Boss'),
	(515, 'Which final boss in Drak\'Tharon Keep transforms into a troll-lich hybrid during the fight?', 'The Prophet Tharon\'ja', 6, 'medium', 'Boss'),
	(516, 'Which troll leader serves as the final boss of the Zul\'Aman raid?', 'Zul\'jin', 8, 'hard', 'Boss'),
	(517, 'Which massive fire elemental guards the entrance to the Black Temple as a boss encounter?', 'Supremus', 8, 'hard', 'Boss'),
	(518, 'Which skeletal dragon is encountered in Naxxramas before fighting Kel\'Thuzad?', 'Sapphiron', 9, 'hard', 'Boss'),
	(519, 'Which boss in Deadmines is known for his pirate theme and parrot companion?', 'Captain Greenskin', 3, 'easy', 'Boss'),
	(520, 'Who is the final boss of the Wailing Caverns dungeon in Classic WoW?', 'Mutanus the Devourer', 3, 'easy', 'Boss'),
	(521, 'Which boss in the Stockades is known for being a leader of the Defias Brotherhood?', 'Bazil Thredd', 3, 'easy', 'Boss'),
	(522, 'Which boss in Shadowfang Keep is a powerful worgen responsible for the curse of the worgen?', 'Archmage Arugal', 3, 'easy', 'Boss'),
	(523, 'Which troll boss leads the forces of Zul\'Farrak?', 'Chief Ukorz Sandscalp', 3, 'easy', 'Boss'),
	(524, 'Which giant ogre serves as a boss in Dire Maul?', 'King Gordok', 3, 'easy', 'Boss'),
	(525, 'Who is the final boss of the Scarlet Halls dungeon?', 'Flameweaver Koegler', 3, 'easy', 'Boss'),
	(526, 'Which mechanical boss serves as the final encounter of Gnomeregan?', 'Mekgineer Thermaplugg', 3, 'easy', 'Boss'),
	(527, 'Which hydra boss is the final encounter of Blackfathom Deeps?', 'Aku\'mai', 3, 'medium', 'Boss'),
	(528, 'Which boss in Ragefire Chasm is a powerful warlock leading the Searing Blade?', 'Jergosh the Invoker', 3, 'easy', 'Boss'),
	(529, 'Which skeletal horse mount, available to Horde players, comes in a red variant?', 'Red Skeletal Horse', 3, 'easy', 'Mounts'),
	(530, 'What mount is given to players who reach exalted with the Darnassus faction?', 'Swift Frostsaber', 3, 'easy', 'Mounts'),
	(531, 'Which mount is the standard starting horse for human characters?', 'Chestnut Mare', 2, 'easy', 'Mounts'),
	(532, 'Which mount is the racial epic wolf mount available to orcs?', 'Swift Gray Wolf', 3, 'easy', 'Mounts'),
	(533, 'Which rare undead horse mount drops from Baron Rivendare in Stratholme?', 'Deathcharger\'s Reins', 3, 'easy', 'Mounts'),
	(534, 'What is the name of the mount available to blood elves as their racial mount?', 'Hawkstrider', 3, 'easy', 'Mounts'),
	(535, 'Which ram mount is available to dwarves as part of their racial mounts?', 'Brown Ram', 2, 'easy', 'Mounts'),
	(536, 'Which ram mount can be earned as a reward during Brewfest?', 'Brewfest Ram', 3, 'easy', 'Mounts'),
	(537, 'Which Alliance PvP mount resembles a mechanical strider?', 'Stormpike Battle Charger', 3, 'easy', 'Mounts'),
	(538, 'What is the undead-specific epic skeletal mount in Classic WoW?', 'Purple Skeletal Warhorse', 3, 'easy', 'Mounts'),
	(540, 'Which mechanical pet is crafted by engineers in Classic WoW?', 'Mechanical Squirrel', 3, 'easy', 'Pets'),
	(541, 'Which tiny dragon companion pet drops from dragonkin mobs in Dustwallow Marsh?', 'Dark Whelpling', 3, 'easy', 'Pets'),
	(542, 'Which rabbit pet is often found during the Noblegarden event?', 'Spring Rabbit', 2, 'easy', 'Pets'),
	(543, 'Which mechanical pet can be acquired by completing a quest in Feralas?', 'Ancona Chicken', 3, 'easy', 'Pets'),
	(544, 'Which rare fishable companion is found in coastal areas of Stranglethorn Vale?', 'Tiny Blue Carp', 3, 'easy', 'Pets'),
	(545, 'Which pet resembles a small, fiery phoenix and is dropped by Kael\'thas?', 'Phoenix Hatchling', 3, 'easy', 'Pets'),
	(546, 'What is the name of the small black cat pet available from the Darkmoon Faire?', 'Darkmoon Cub', 2, 'easy', 'Pets'),
	(547, 'Which pet can be obtained by fishing in the waters of Zangarmarsh?', 'Toad', 3, 'easy', 'Pets'),
	(548, 'Which raptor pet can be obtained by killing the rare spawn Gundrak Raptor in Northrend?', 'Gundrak Hatchling', 3, 'easy', 'Pets'),
	(549, 'Which profession allows players to create potions, flasks, and elixirs?', 'Alchemy', 2, 'easy', 'Professions'),
	(550, 'What gathering profession involves mining nodes of ores and gems?', 'Mining', 2, 'easy', 'Professions'),
	(551, 'Which profession allows you to create cloth armor and bags?', 'Tailoring', 2, 'easy', 'Professions'),
	(552, 'Which profession allows players to craft mail and plate armor?', 'Blacksmithing', 2, 'easy', 'Professions'),
	(553, 'Which crafting profession specializes in leather and mail gear?', 'Leatherworking', 2, 'easy', 'Professions'),
	(554, 'Which profession is responsible for enchanting gear and crafting wands?', 'Enchanting', 2, 'easy', 'Professions'),
	(555, 'Which gathering profession allows you to gather herbs for alchemy?', 'Herbalism', 2, 'easy', 'Professions'),
	(556, 'Which profession is known for creating mechanical pets and gadgets?', 'Engineering', 2, 'easy', 'Professions'),
	(557, 'Which secondary profession allows players to fish in bodies of water?', 'Fishing', 2, 'easy', 'Professions'),
	(558, 'What profession allows players to create jewels and gems for socketed items?', 'Jewelcrafting', 3, 'easy', 'Professions'),
	(559, 'Which rare pattern allows blacksmiths to craft the legendary weapon Sulfuras?', 'Plans: Sulfuron Hammer', 9, 'hard', 'Professions'),
	(560, 'Which herbalism node in Outland provides Terocone, a key ingredient in high-level potions?', 'Terocone', 8, 'hard', 'Professions'),
	(561, 'Which rare tailoring pattern allows players to craft the Robe of the Void?', 'Pattern: Robe of the Void', 9, 'hard', 'Professions'),
	(562, 'Which rare alchemy recipe is required to craft the Flask of the Titans?', 'Recipe: Flask of the Titans', 8, 'hard', 'Professions'),
	(563, 'Which legendary engineering item grants players temporary increased speed and rocket boosts?', 'Gnomish Rocket Boots', 9, 'hard', 'Professions'),
	(564, 'Which rare mining vein in Outland can yield Eternium Ore?', 'Rich Adamantite Vein', 8, 'hard', 'Professions'),
	(565, 'Which fishing item is required to summon Gahz\'ranka in Zul\'Gurub?', 'Mudskunk Lure', 9, 'hard', 'Professions'),
	(566, 'Which rare jewelcrafting design teaches players to cut the Brilliant Lionseye gem?', 'Design: Brilliant Lionseye', 9, 'hard', 'Professions'),
	(567, 'Which leatherworking pattern is needed to craft the Devilsaur Gauntlets?', 'Pattern: Devilsaur Gauntlets', 9, 'hard', 'Professions'),
	(568, 'Which rare tailoring pattern in Stranglethorn Vale allows players to craft Bloodvine gear?', 'Pattern: Bloodvine Leggings', 9, 'hard', 'Professions'),
	(570, 'Which city is located in the Wetlands and serves as a port for ships to Theramore?', 'Menethil Harbor', 3, 'easy', 'City'),
	(574, 'Which ancient night elf capital, destroyed during the Sundering, lies beneath the Well of Eternity?', 'Zin-Azshari', 8, 'hard', 'City'),
	(576, 'Which ruined human capital was destroyed during the Third War and now houses the Forsaken?', 'Lordaeron', 9, 'hard', 'City'),
	(578, 'Which underwater naga capital was first revealed during Battle for Azeroth?', 'Nazjatar', 9, 'hard', 'City'),
	(579, 'Which class can summon a Doomguard using the Ritual of Doom spell?', 'Warlock', 8, 'hard', 'Class'),
	(580, 'Which class has the unique ability to teleport directly to Moonglade?', 'Druid', 7, 'hard', 'Class'),
	(581, 'Which class can use "Misdirection" to transfer threat to a friendly tank?', 'Hunter', 8, 'hard', 'Class'),
	(582, 'Which WotLK death knight ability absorbs healing from its target?', 'Necrotic Strike', 9, 'hard', 'Class'),
	(583, 'Which priest specialization is known for high AoE damage through Shadow Word: Pain?', 'Shadow', 8, 'hard', 'Class'),
	(584, 'Which shaman ability gives them the power to resurrect themselves after death?', 'Reincarnation', 8, 'hard', 'Class'),
	(585, 'Which mage talent tree focuses on fire-based abilities such as Pyroblast?', 'Fire', 7, 'hard', 'Class'),
	(586, 'Which paladin ability is known for granting immunity to incoming spells?', 'Divine Shield', 9, 'hard', 'Class'),
	(587, 'Which rogue specialization focuses on poisons and utility in PvP scenarios?', 'Assassination', 8, 'hard', 'Class'),
	(588, 'Which ability allows warriors to temporarily gain 50% increased damage from critical hits?', 'Enrage', 9, 'hard', 'Class'),
	(589, 'Which dungeon located in Westfall is home to the Defias Brotherhood?', 'Deadmines', 3, 'easy', 'Dungeon'),
	(590, 'Which dungeon in Tirisfal Glades features undead enemies and necromancers?', 'Scarlet Monastery', 3, 'easy', 'Dungeon'),
	(591, 'Which dungeon is located in the Swamp of Sorrows and features Twilight\'s Hammer cultists?', 'The Temple of Atal\'Hakkar', 3, 'easy', 'Dungeon'),
	(592, 'Which dungeon is home to Warlord Zaela and the Blackrock clan in Cataclysm?', 'Blackrock Caverns', 3, 'easy', 'Dungeon'),
	(593, 'Which dungeon in Silverpine Forest features worgen enemies?', 'Shadowfang Keep', 2, 'easy', 'Dungeon'),
	(594, 'Which dungeon in the Plaguelands is known for Darkmaster Gandling and necromantic foes?', 'Scholomance', 8, 'hard', 'Dungeon'),
	(595, 'Which dungeon located in the Swamp of Sorrows is home to the Atal\'ai trolls?', 'Sunken Temple', 9, 'hard', 'Dungeon'),
	(596, 'Which dungeon in Outland contains the fel orc Keli\'dan the Breaker?', 'Hellfire Ramparts', 8, 'hard', 'Dungeon'),
	(597, 'Which Northrend dungeon involves fighting the Blue Dragonflight and their leader, Ley-Guardian Eregos?', 'The Oculus', 8, 'hard', 'Dungeon'),
	(598, 'Which dungeon within the ruined city of Stratholme features Baron Rivendare as its final boss?', 'Stratholme', 9, 'hard', 'Dungeon'),
	(599, 'Which world event during Brewfest allows players to compete in a drinking contest?', 'The Brew of the Month Club', 5, 'medium', 'Event'),
	(600, 'Which world event is tied to celebrating Azeroth\'s harvest and giving thanks?', 'Harvest Festival', 5, 'medium', 'Event'),
	(601, 'Which in-game event features battling the Headless Horseman during October?', 'Hallow\'s End', 5, 'medium', 'Event'),
	(602, 'Which faction is composed of night elves and works to protect nature?', 'Cenarion Circle', 3, 'easy', 'Faction'),
	(603, 'Which faction of dwarves focuses on archaeology and Titan discoveries?', 'Explorers\' League', 3, 'easy', 'Faction'),
	(604, 'Which faction in Outland opposes the Burning Legion and resides in Shattrath City?', 'The Aldor', 3, 'easy', 'Faction'),
	(605, 'Which faction in Classic WoW defends Azeroth from the Scourge and undead?', 'Argent Dawn', 3, 'easy', 'Faction'),
	(606, 'Which faction of trolls resides in Zul\'Aman?', 'Amani Tribe', 4, 'easy', 'Faction'),
	(607, 'Which faction is composed of members seeking to end all life on Azeroth?', 'Twilight\'s Hammer', 8, 'hard', 'Faction'),
	(608, 'Which faction serves the Lich King during Wrath of the Lich King?', 'The Scourge', 8, 'hard', 'Faction'),
	(609, 'Which ancient troll empire once ruled large parts of the Eastern Kingdoms?', 'Zandalari', 8, 'hard', 'Faction'),
	(610, 'Which faction works to counter the naga threat in Zangarmarsh during The Burning Crusade?', 'Cenarion Expedition', 8, 'hard', 'Faction'),
	(611, 'Which item restores health and mana and is commonly used by healers in Classic WoW?', 'Major Mana Potion', 3, 'easy', 'Items'),
	(612, 'What is the name of the reagent needed by Druids to cast Rebirth in Classic WoW?', 'Maple Seed', 2, 'easy', 'Items'),
	(613, 'Which consumable food item restores health over time and is created through cooking?', 'Spiced Wolf Meat', 2, 'easy', 'Items'),
	(614, 'Which item is required to enter Onyxia\'s Lair in Classic WoW?', 'Drakefire Amulet', 3, 'easy', 'Items'),
	(615, 'Which mount item is dropped by Baron Rivendare in Stratholme?', 'Deathcharger\'s Reins', 3, 'easy', 'Items'),
	(616, 'Which fishing item grants increased underwater breathing?', 'Aquadynamic Fish Attractor', 5, 'medium', 'Items'),
	(617, 'Which key item is needed to unlock the door to Scholomance in Classic WoW?', 'Skeleton Key', 6, 'medium', 'Items'),
	(618, 'Which healing trinket in The Burning Crusade is purchased from G\'eras in Shattrath City?', 'Tear of Heaven', 5, 'medium', 'Items'),
	(619, 'Which rare tailoring material from ZG is used in crafting Bloodvine gear?', 'Bloodvine', 6, 'medium', 'Items'),
	(620, 'Which item is used by hunters to improve pet loyalty and training in Classic WoW?', 'Training Manual', 6, 'medium', 'Items'),
	(621, 'Which legendary weapon was crafted using Shadowfrost Shards in WotLK?', 'Shadowmourne', 9, 'hard', 'Items'),
	(622, 'Which rare item dropped by Kael\'thas Sunstrider in TBC starts the Ashes of Al\'ar quest?', 'Verdant Sphere', 8, 'hard', 'Items'),
	(623, 'Who is known as the Earth-Warder among the Dragon Aspects?', 'Neltharion', 3, 'easy', 'Lore'),
	(624, 'Who is the orc warchief responsible for founding Orgrimmar?', 'Thrall', 3, 'easy', 'Lore'),
	(625, 'Which human king led the Alliance during the events of Wrath of the Lich King?', 'King Varian Wrynn', 3, 'easy', 'Lore'),
	(626, 'Which Elven kingdom was destroyed by the Scourge, leading to the formation of the Forsaken?', 'Quel\'Thalas', 3, 'easy', 'Lore'),
	(627, 'Who was the first Lich King before Arthas Menethil?', 'Ner\'zhul', 3, 'easy', 'Lore'),
	(628, 'Which quest in Elwynn Forest requires players to investigate the Defias Brotherhood?', 'The Defias Brotherhood', 3, 'easy', 'Quests'),
	(629, 'Which Classic quest involves slaying Hogger in Elwynn Forest?', 'Wanted: Hogger', 3, 'easy', 'Quests'),
	(630, 'Which quest chain in Westfall reveals the leader of the Defias Brotherhood?', 'VanCleef\'s Betrayal', 3, 'easy', 'Quests'),
	(631, 'What quest requires players to retrieve stolen pumpkins from Defias Thieves?', 'Poor Old Blanchy', 2, 'easy', 'Quests'),
	(632, 'Which quest in Durotar involves players hunting down scorpions for venom samples?', 'Sting of the Scorpid', 3, 'easy', 'Quests'),
	(633, 'Which TBC quest chain leads players to the summoning of Nightbane in Karazhan?', 'Nightbane Summoning', 3, 'easy', 'Quests'),
	(634, 'Which quest in Nagrand helps players reunite Thrall with his grandmother?', 'The Hero of the Mag\'har', 3, 'easy', 'Quests'),
	(635, 'Which Classic WoW quest requires players to escort the lost druid from the Wailing Caverns?', 'Leaders of the Fang', 3, 'easy', 'Quests'),
	(636, 'Which WotLK quest chain involves defending Wyrmrest Temple from Malygos\'s forces?', 'Defending Wyrmrest Temple', 3, 'easy', 'Quests'),
	(637, 'Which daily quest in Northrend allows players to joust during the Argent Tournament?', 'A Blade Fit for a Champion', 3, 'easy', 'Quests'),
	(638, 'Which quest in the Burning Steppes requires players to gather dragonkin scales?', 'Dragonkin Menace', 5, 'medium', 'Quests'),
	(639, 'Which WotLK quest chain involves helping Drakuru take control of Zul\'Drak?', 'Betrayal', 5, 'medium', 'Quests'),
	(640, 'Which quest chain involves collecting fragments of the Scepter of the Shifting Sands?', 'The Scepter of the Shifting Sands', 5, 'medium', 'Quests'),
	(641, 'Which quest chain leads players to confront the Scarlet Crusade leader in Stratholme?', 'In the Shadow of the Light', 6, 'medium', 'Quests'),
	(642, 'Which quest chain in the Eastern Plaguelands involves helping the ghost of Pamela Redpath?', 'Little Pamela', 8, 'hard', 'Quests'),
	(643, 'Which quest line in the Burning Crusade rewards players with the Shattered Sun title?', 'The Battle for Sunwell Plateau', 8, 'hard', 'Quests'),
	(644, 'Which Classic quest chain rewards players with the legendary item Thunderfury?', 'Bindings of the Windseeker', 9, 'hard', 'Quests'),
	(645, 'Which quest chain involves attuning players to the Black Temple in TBC?', 'The Black Temple Attunement', 9, 'hard', 'Quests'),
	(646, 'Which WotLK quest chain involves the betrayal of Drakuru and the cleansing of Gundrak?', 'Betrayal at Zul\'Drak', 8, 'hard', 'Quests'),
	(647, 'Which quest chain involves the creation of the legendary healing mace Val\'anyr?', 'The Hands of the Makers', 10, 'hard', 'Quests'),
	(648, 'Which TBC quest requires players to defeat Doomwalker near the Black Temple?', 'The Doomwalker Has Fallen', 9, 'hard', 'Quests'),
	(649, 'Which quest line involves recovering the ancient hammer Sulfuras in Molten Core?', 'Sulfuras, Hand of Ragnaros', 10, 'hard', 'Quests'),
	(650, 'Which epic quest chain in WotLK leads to the unlocking of Algalon the Observer?', 'Heroic: The Celestial Planetarium', 10, 'hard', 'Quests'),
	(651, 'Which quest chain in the Plaguelands leads to the epic battle at Light\'s Hope Chapel?', 'The Light\'s Hope Chapel Defense', 9, 'hard', 'Quests'),
	(652, 'Which race is known for their affinity with nature and their connection to Elune?', 'Night Elves', 3, 'easy', 'Race'),
	(653, 'Which race hails from Mulgore and is known for their totemic culture?', 'Tauren', 3, 'easy', 'Race'),
	(654, 'Which race of humans founded the kingdom of Stormwind?', 'Humans', 3, 'easy', 'Race'),
	(655, 'Which race of gnomes originally lived in Gnomeregan before being displaced?', 'Gnomes', 3, 'easy', 'Race'),
	(656, 'Which race, introduced in TBC, is known for their connection to the Naaru?', 'Draenei', 6, 'medium', 'Race'),
	(657, 'Which troll tribe allied with the Horde during Thrall\'s leadership?', 'Darkspear', 6, 'medium', 'Race'),
	(658, 'Which Northrend-based race are known as the taunka and resemble tauren?', 'Taunka', 6, 'medium', 'Race'),
	(659, 'Which ancient race of elves served Azshara before the Great Sundering?', 'Highborne', 9, 'hard', 'Race'),
	(660, 'Which race of stone constructs was created by the Titans to serve Azeroth\'s defense?', 'Earthen', 8, 'hard', 'Race'),
	(661, 'Which trinket, dropped by Hydross the Unstable in Serpentshrine Cavern, enhances healing?', 'Living Root of the Wildheart', 5, 'medium', 'Items');

-- Create the trivia_achievement_progress table if it doesn't already exist
CREATE TABLE IF NOT EXISTS `trivia_achievement_progress` (
    player_guid INT PRIMARY KEY,
    correct_answers INT DEFAULT 0,
    speed_correct_answers INT DEFAULT 0,
    category_votes INT DEFAULT 0,
    difficulty_votes INT DEFAULT 0,
    hint_requests INT DEFAULT 0,
    session_participation INT DEFAULT 0,
    night_sessions INT DEFAULT 0,
    morning_sessions INT DEFAULT 0,
    categories_correct TEXT DEFAULT NULL,
    minimal_hint_sessions INT DEFAULT 0,
    current_streak INT DEFAULT 0,
    perfect_session_questions INT DEFAULT 0,
    comeback_streak INT DEFAULT 0
);

DELETE FROM `trivia_achievement_progress`;

-- Tie the title rewards to the achievements
USE `acore_world`;
DELETE FROM `achievement_reward` WHERE ID BETWEEN 9001 and 9023;
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9001, 200, 200, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9002, 197, 197, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9003, 199, 199, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9004, 203, 203, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9005, 196, 196, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9006, 202, 202, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9007, 198, 198, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9008, 194, 194, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9009, 195, 195, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9014, 204, 204, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9015, 205, 205, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9016, 206, 206, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9017, 207, 207, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9018, 208, 208, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9019, 209, 209, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9020, 210, 210, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9021, 211, 211, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9022, 212, 212, 0, 0, '', '', 0);
INSERT INTO `achievement_reward` (`ID`, `TitleA`, `TitleH`, `ItemID`, `Sender`, `Subject`, `Body`, `MailTemplateID`) VALUES (9023, 213, 213, 0, 0, '', '', 0);