
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for rand_dung_augment_creature_info
-- ----------------------------
DROP TABLE IF EXISTS `rand_dung_augment_creature_info`;
CREATE TABLE `rand_dung_augment_creature_info` (
  `creatureID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of rand_dung_augment_creature_info
-- ----------------------------
INSERT INTO `rand_dung_augment_creature_info` VALUES ('19259');

-- ----------------------------
-- Table structure for rand_dung_augment_spell_choice_info
-- ----------------------------
DROP TABLE IF EXISTS `rand_dung_augment_spell_choice_info`;
CREATE TABLE `rand_dung_augment_spell_choice_info` (
  `classID` int(11) NOT NULL,
  `spellID` int(11) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of rand_dung_augment_spell_choice_info
-- ----------------------------
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '11578', 'Warrior - Charge');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '48819', 'Paladin - Consecration');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '34026', 'Hunter - Kill Command');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '48691', 'Rogue - Ambush');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '48158', 'Priest - Shadow Word: Death');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '49941', 'Death Knight - Blood Boil');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '49231', 'Shaman - Earth Shock');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('8', '44781', 'Mage - Arcane Barrage');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '47813', 'Warlock - Corruption');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('8', '42897', 'Mage - Arcane Blast');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('8', '42891', 'Mage - Pyroblast');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('8', '47610', 'Mage - Frostfire Bolt');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('8', '42842', 'Mage - Frostbolt');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('8', '42945', 'Mage - Blast Wave');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('8', '2139', 'Mage - Counterspell');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '34433', 'Priest - Shadowfiend');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '15487', 'Priest - Silence');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '48127', 'Priest - Mind Blast');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '48300', 'Priest - Devouring Plague');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '48156', 'Priest - Mind Flay');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '48063', 'Priest - Greater Heal');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '48068', 'Priest - Renew');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('5', '48066', 'Priest - Power Word: Shield');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '47486', 'Warrior - Mortal Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '47465', 'Warrior - Rend');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '57755', 'Warrior - Heroic Throw');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '23881', 'Warrior - Bloodthirst');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '47475', 'Warrior - Slam');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '34428', 'Warrior - Victory Rush');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '1680', 'Warrior - Whirlwind');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '47488', 'Warrior - Shield Slam');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '47498', 'Warrior - Devastate');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '57823', 'Warrior - Revenge');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('1', '47502', 'Warrior - Thunder Clap');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '48785', 'Paladin - Flash of Light');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '48801', 'Paladin - Exorcism');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '48782', 'Paladin - Holy Light');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '10308', 'Paladin - Hammer of Justice');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '53595', 'Paladin - Hammer of the Righteous');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '35395', 'Paladin - Crusader Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '53385', 'Paladin - Divine Storm');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '53407', 'Paladin - Judgement');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '20271', 'Paladin - Judgement');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('2', '53408', 'Paladin - Judgement');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '49050', 'Hunter - Aimed Shot');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '19574', 'Hunter - Bestial Wrath');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '49045', 'Hunter - Arcane Shot');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '53209', 'Hunter - Chimera Shot');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '61006', 'Hunter - Kill Shot');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '49048', 'Hunter - Multi-Shot');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '49001', 'Hunter - Serpent Sting');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '5116', 'Hunter - Concussive Shot');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '63672', 'Hunter - Black Arrow');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '49052', 'Hunter - Steady Shot');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '60053', 'Hunter - Explosive Shot');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '53339', 'Hunter - Mongoose Bite');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('3', '48996', 'Hunter - Raptor Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '47864', 'Warlock - Curse of Agony');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '47860', 'Warlock - Death Coil');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '47843', 'Warlock - Unstable Affliction');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '59164', 'Warlock - Haunt');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '59172', 'Warlock - Chaos Bolt');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '17962', 'Warlock - Conflagurate');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '47827', 'Warlock - Shadowburn');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '61290', 'Warlock - Shadowflame');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '47847', 'Warlock - Shadowfury');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '47838', 'Warlock - Incinerate');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('9', '47811', 'Warlock - Immolate');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '57993', 'Rogue - Envenom');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '48668', 'Rogue - Eviscerate');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '48676', 'Rogue - Garrote');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '48672', 'Rogue - Rupture');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '14278', 'Rogue - Ghostly Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '48657', 'Rogue - Backstab');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '48638', 'Rogue - Sinister Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '51723', 'Rogue - Fan of Knives');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '48660', 'Rogue - Hemorrhage');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '6774', 'Rogue - Slice and Dice');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('4', '8647', 'Rogue - Expose Armor');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '49271', 'Shaman - Chain Lightning');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '49233', 'Shaman - Flame Shock');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '61657', 'Shaman - Fire Nova');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '49236', 'Shaman - Frost Shock');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '60102', 'Shaman - Lava Lash');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '57994', 'Shaman - Wind Shear');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '17364', 'Shaman - Stormstrike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '49273', 'Shaman - Healing Wave');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '55459', 'Shaman - Chain Heal');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '49273', 'Shaman - Lesser Healing Wave');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('7', '61301', 'Shaman - Riptide');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '55262', 'Death Knight - Heart Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '48982', 'Death Knight - Rune Tap');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '45524', 'Death Knight - Chains of Ice');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '55268', 'Death Knight - Frost Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '51411', 'Death Knight - Howling Blast');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '49909', 'Death Knight - Icy Touch');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '51425', 'Death Knight - Obliterate');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '51328', 'Death Knight - Corpse Explosion');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '49576', 'Death Knight - Death Grip');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '49895', 'Death Knight - Death Coil');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '49924', 'Death Knight - Death Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '49921', 'Death Knight - Plague Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('6', '55271', 'Death Knight - Scourge Strike');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48463', 'Druid - Moonfire');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48468', 'Druid - Insect Swarm');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '53201', 'Druid - Starfall');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48465', 'Druid - Starfire');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48461', 'Druid - Wrath');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48570', 'Druid - Claw');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48577', 'Druid - Ferocious Bite');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48568', 'Druid - Lacerate');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48564', 'Druid - Mangle (Bear)');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48566', 'Druid - Mangle (Cat)');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48480', 'Druid - Maul');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48574', 'Druid - Rake');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48579', 'Druid - Ravage');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '49800', 'Druid - Rip');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48572', 'Druid - Shred');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48378', 'Druid - Healing Touch');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48451', 'Druid - Lifebloom');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '50464', 'Druid - Nourish');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48443', 'Druid - Regrowth');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '48441', 'Druid - Rejuvenation');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '18562', 'Druid - Swiftmend');
INSERT INTO `rand_dung_augment_spell_choice_info` VALUES ('11', '53251', 'Druid - Wild Growth');

-- ----------------------------
-- Table structure for rand_dung_augment_spell_info
-- ----------------------------
DROP TABLE IF EXISTS `rand_dung_augment_spell_info`;
CREATE TABLE `rand_dung_augment_spell_info` (
  `classID` int(11) DEFAULT NULL,
  `spellID` int(11) DEFAULT NULL,
  `Description` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of rand_dung_augment_spell_info
-- ----------------------------
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '49906', 'Deals Frost damage to an enemy target.  Causes triple damage against Frozen targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '49883', 'Targets in a cone in front of the caster take 2000 Fire damage over 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '49938', 'Corrupts the ground targeted by the Death Knight, causing 62 Shadow damage every sec that targets remain in the area for 10 seconds.  This ability produces a high amount of threat.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '49941', 'Boils the blood of all enemies within $a1 yards, dealing 220 Shadow damage.  Deals additional damage to targets infected with Blood Plague or Frost Fever.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '49961', 'Blinks to an enemy inflicting 385 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '49999', 'A deadly attack that deals 75% weapon damage plus 256 and heals the Death Knight for 15% of maximum health.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '59164', 'You send a ghostly soul into the target, dealing 753 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 seconds. When the Haunt spell ends or is dispelled, the soul returns to you, healing you ');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '50111', 'When you are above 75% health, you deal 10% more damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '50257', 'Blasts the target with scalding water, inflicting 956 Fire damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '50273', 'Launches several missiles at the enemy target, inflicting Arcane damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '50288', 'You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 20 yards of the enemy target. Maximum 20 stars. Lasts 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '43996', 'Inflicts $s1 Nature damage to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '43983', 'Creates a fierce energy storm that reacts to nearby enemy players, zapping them with electricity when they cast spells.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '37328', 'Burns the enemy for Arcane damage and inflicts additional damage over 12 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '12611', 'Inflicts Frost damage to enemies in a cone in front of the caster, reducing their movement speed for 8 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '75362', 'Strikes an enemy with a lightning bolt that arcs to another nearby enemy. The spell affects up to 6 targets, inflicting greater Nature damage to each successive target.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '40585', 'A barrage of demonic magic deals 3000 Shadow damage to the target every 1 sec for 10 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '40599', 'Lashes out in a vicious arc, inflicting normal damage plus 125 to enemies in a cone in front of the caster.  Also reduces healing effects by -50%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '40611', 'Leaves a blazing fire on the ground that deals 5000 Fire damage to nearby enemies every 3 sec.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '56319', 'Inflicts 850 Nature damage every 1 sec over 8 seconds to enemies who enter the area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '41479', 'Teleports the caster a random distance away.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '41573', 'Deals 30 Nature to the target and all nearby enemies.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '49703', 'Inflicts 2250 Nature damage and an additional 580 damage every 2 sec. to enemies in a cone in front of the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '60802', 'Crushes your target, inflicting 150% melee damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '60919', 'Cause a shower of rocks and debris to pelt the targetted area.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '60985', 'Zaps an enemy for 800 Shadow damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '61016', 'Strikes an enemy with shadow lightning that arcs to another nearby enemy. The spell affects up to 3 targets.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '61084', 'Teleports the caster to a nearby random location, removing all negative effects from the caster.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '61098', 'Summons an entire horde of zombies to fight for the Death Knight.  The zombies will swarm the area, fighting anything they can.  While channelling Zombie Horde, the caster takes -50% less damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '61162', 'Inflicts 5287 Fire damage to an enemy, and causing 3500 additional damage per 3 sec for 9 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '61227', 'Jumps at the target, inflicting 850% weapon damage.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '61272', 'Blasts an enemy with arcane energies, inflicting 26437 Arcane damage per 1 sec. for 3 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '61301', 'Heals a friendly target for 1736 and another 1670 over 15 seconds.  Your next Chain Heal cast on that primary target within 15 seconds will consume the healing over time effect and increase the amount of the Chain Heal by 25%.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '61489', 'Heals 951 every second and 2687 when effect finishes or is dispelled.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '68594', 'Heals the shielded target for 64500.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('1', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('2', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('3', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('4', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('5', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('6', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('7', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('8', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('9', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
INSERT INTO `rand_dung_augment_spell_info` VALUES ('11', '68832', 'Fires a ball of napalm, dealing 3172 Fire damage to all enemies within $67444a1 yards of the impact. In addition, targets will be covered in napalm, dealing 3000 Fire per second for 5 seconds.');
