--[[
Set NPC idle chat text

This can be achieved by using

{"Text1", "Text2", "Text3",},
to set up a continuous conversation

Note: Do not change the content in [0] = {} below

]]--

local text = {[0] = {1,1},

----------------------Start adding chat text here-------------------------
"Selling Silver Scales Breastplate, 5G each.",
{"Selling epic weapon, slightly used. Only dropped once...per boss fight.", "How many bosses has it survived?", "Let's just say it's seen more floors than a janitor.", "That weapon's got more history than the Scarlet Monastery.", "Epic weapon or archaeology artifact?"},
{"WTB someone to carry me through a dungeon. Offering friendship and my eternal gratitude.", "Is that gratitude epic quality?", "Only if you don't let me die.", "Gratitude and a side of repair bills, coming up!", "Best deal in Azeroth!"},
{"WTS invisibility potions. Perfect for ninja looting!", "Do they work on guildmates?", "Only if they don't have anti-ninja goggles.", "Ninja loot now, apologize later.", "Invisibility: the gift that keeps on giving."},
{"Auctioning off a date with my main character. Comes with a free mount ride!", "Is the mount epic at least?", "Of course, and it's got two seats!", "Hope the mount's more reliable than my last date...", "Romance, WoW style."},
{"WTS rare pet. Slightly disobedient but has character.", "Does it do tricks?", "Only when it's not busy ignoring my commands.", "Does it come with a manual?", "Rare pet with an attitude, a bargain!"},
{"Looking to trade my soul for epic gear. Any takers?", "Is the soul epic quality?", "Depends, does frequent dying lower its value?", "Gear first, soul later. No refunds!", "Best trade of my afterlife!"},
{"WTS stack of [Mystery Meat]. Not responsible for any side effects.", "What kind of side effects are we talking?", "Uncontrollable dancing, mostly.", "Perfect for my next raid!", "Dine and dance with [Mystery Meat]!"},
{"WTB luck potion. My drop rates are cursed.", "Can't sell you luck, but I have a four-leaf clover.", "Does it work in raids?", "Only if you rub it and chant the loot prayer.", "Loot luck, now in potion form!"},
{"Selling a slightly haunted helmet. Previous owner's spirit included.", "Does it give extra wisdom?", "Only if you consider moaning at midnight wise.", "I'll take it for the ghost stories alone!", "Haunted helmet, the real spooky deal!"},
{"WTB a map to find my way out of Wailing Caverns.", "You mean you're still stuck in there?", "Since last Tuesday... Send help.", "I'll trade you for a breadcrumb trail.", "Wailing Caverns: the maze you never escape."},
{"WTS [Mysterious Potion]. Effects may vary. No refunds.", "May vary? Like how?", "Last guy turned into a sheep for an hour.", "That's some baa-d luck.", "Sheep today, who knows tomorrow!"},
{"Looking for a mage to conjure me a sandwich. Starving here!", "What kind of sandwich are we talking?", "Anything that doesn't taste like mana.", "One conjured ham on rye, coming up!", "Magic meals, just a spell away."},
{"WTS invisible cloak. Disclaimer: Might not actually be invisible.", "How do we know it's not just an empty hanger?", "You just have to believe!", "I bought one, now I can't find it...", "The best cloak you'll never see!"},
{"WTB the patience to deal with pugs.", "Isn't that sold out everywhere?", "I'd settle for a pug that knows north from south.", "How about a compass instead?", "Pugs: where every direction is pull!"},
{"WTS [Bag of Laughs]. Contents: dad jokes and puns.", "How effective are they?", "Let's just say you'll groan more than laugh.", "Perfect for my next guild meeting!", "Laughter is the best loot."},
{"WTS Time-Lost Artifacts. Disclaimer: May actually just be junk.", "Define 'artifact'.", "It's very ancient... looking.", "So, like, last expansion ancient?", "Time-Lost or simply forgotten!"},
"Buying Air for 400G a set, buying [Frozen Orb] for 100 each.",
{"Anyone know a good spot for farming [Heavy Leather]? Need a bunch for crafting.", "Try the raptors in Wetlands. Decent drop rate there.", "Thanks for the tip! Need anything in return?", "No worries, just pay it forward to the next crafter in need."},
{"Looking for advice on the best tanking gear for early raids.", "You should focus on increasing your stamina and armor stats.", "Got it. Any specific dungeons I should run?", "Try running Blackrock Depths. It has some solid gear drops for tanks."},
{"Struggling with the final boss in Maraudon. Any tips?", "What class are you playing?", "Resto druid.", "Keep your HoTs up and watch out for area damage. Kiting helps too.", "Great, I'll give that a try. Thanks!"},
{"Does anyone have experience with the auction house? Not sure how to price my items.", "It depends on the item. Check what others are selling it for as a start.", "Should I go higher or lower than the average?", "Match the average. Going too low undervalues your item, too high and it won't sell."},
{"LF someone experienced with herbalism to help identify a few plants.", "I can help you out. What did you find?", "Not sure, found them in Ashenvale. They're sort of purple and spiky.", "Sounds like Gromsblood. It's quite valuable, good find!"},
{"Any guilds out there good for new players? Just started a week ago.", "Welcome to the game! What's your class and level?", "Level 15 warrior. Still figuring things out.", "Our guild is newbie-friendly. We do regular dungeon runs and help with quests."},
{"Can anyone recommend a good leveling route for Eastern Kingdoms?", "Start with Redridge Mountains, then Duskwood. Great quests there.", "Should I avoid PvP areas?", "If you're not into PvP, yeah. Stick to safer zones like Loch Modan."},
{"Looking for a group to do some casual battlegrounds. Not super competitive, just for fun.", "Count me in! I'm tired of the serious PvP grind.", "Great! Let's just enjoy the game and have some laughs.", "Sounds good. Let's keep it light and fun."},
"%role% looking for weekend raid team",
"Anyone for leveling in %zone%?",
"How many people needed to raid SW?",
"Looking for a questing partner in %zone%.",
"<Sentinel> is now recruiting. We require a 4500+ GS and max professions. Raid times are Tuesday, Wednesday evening 8 to 11:30. We are mostly looking to fill 10-man team positions.",
"Buying Titan Ore, whisper.",
"LFM for %zone% questing.",
"LF party in %zone%.",
"I hate questing in %zone%. Where can i go instead for my level?",
"25 NAXX5 group, quick run. explosive DPS needed...",
"LFM for UBRS Jed/Rend runs. First Briarwood Reed res.",
"[Simple Cape] for sale at a very low price",
"LFM 25-man Ulduar FL run. Need some high gearscores",
"%role% looking for a pvp friend",
"LF arena partner for 2s. 1880+ only please.",
"LF 3s carry.",
"Can 10 people manage SW?",
"LFM for BWL. no laggy connections, need all classes. Bads will be booted.",
"10-man Black Dragon, any SM, NQ, SS?",
"<Eight Memories> is a new guild recruiting. We run DKP and are open to all players, no gear requirements. Active raid times TBD.",
"LFM BRD Lava run. Need %role%.",
"%instance% looking for T, %role%, DPS",
"SW transmog contest forming! Come and get all the prizes!",
"Buying a [Combustion Bracers], selling offers",
"25 NAXX5 group, fast recruitment, explosive DPS needed",
"Buying [Infinite Dust] [Infinite Dust]",
"10 ULD, looking for 4100+ melee and NQ, MS",
"Selling G, selling G, pm for details",
"10-man Ulduar, looking for DPS and %role%",
"[Glory of the Ulduar Raider (10-man)] half-achievement team. 4 guardians starting. Looking for NQ, dual SMSS with GSMMMMM",
"25 NAXX,...........5 group, looking for DPS, melee and ranged who need trinkets, hurry up",
"10-man ULD new CD!! Looking for strong NQ!! MS!!! And ZS!!! Strong crushing team!! Bring GS 7=3 at least till UG",
"%instance% looking for strong T and DPS, last wave, hurry up",
"Anyone for 25-man RS?",
"Buying Eternal Fire 20! Air 15! Earth 6! Shadow 5! Water 4! Life 30! Saronite Ore 15! Saronite Bar 30! Borean Leather 20/set Thick Borean Leather 130/set Icy Dragonscale 1G Nerubian Chitin 1G Icy Fang 2G Frozen Orb 100 Rune Orb 210! COD accepted.",
"[Frostweave Cloth] [Borean Leather] 25 sets each, contact if needed",
"Hero League 2 team preparing for TOC recruiting. Inviting friends to experience game fun. DM if interested.",
"[Frozen Orb]=110G, [Azure Thread]=32G!!",
"BWL transmog team, contact if interested, already 2 people, no AL",
"Daily R-point size game, 200G a round, contact if interested",
"Lao Pao Er guild, gathering two 10-man ULD full-clear teams. Preparing for TOC, recruiting DZ, AM, NQ, Evil DK, main force upon joining. Requires some equipment foundation, new team members double points for bosses. Give me a stable you and I give you a quality",
"YXSL, new progress, daily raid, looking for 4000+ %role%s, magic DPS, LR, contact if interested",
"YXSL, looking for 4000+ %role%s, magic DPS, LR, contact if interested",
"Buying King's Shadow Amber Scarlet Stone Fear Purple Yellow Crystal 120G Frostweave 4G Icethorn Snake Venom 32g Witchflower 151G/set Damaged Necklace 88g support COD",
"<Golden Times> recruiting elite players of all classes~ All-heart DKP new CD welcomes all class masters to join, let us feel the friendship and joy that WoW once brought us, activity time 456 every night 8-11~ waiting for you to join!",
"1:150G selling 100 Crystal Coins. If needed, contact me.",
"Selling/crafting Ulduar 226 ilvl cloth leather mail plate crafting belts and shoes, buying Frozen Orb 100g Rune Orb 220g King's Amber Scarlet Red Fear Stone Purple Yellow Crystal 121g Titansteel Ore 125g Saronite Ore 15g, Earth 7.1 Fire 26.5 Air 16 Shadow 5 Water",
"Buying Eternal Earth 7G Eternal Life 32G/group Fire 26 Air 16 Shadow 5 Water 7 Saronite 15.5 Titan 126 Frozen Orb 101 Borean Leather 22G Spider Silk Ice Bug Leather 1.5 support COD instant purchase",
"Buying 150 Witchflower, support mail",
"HSL looking for T and DPS",
"Selling account 80DK dual-gathering max dual-spec cheap sale interested MMM same account 3 classes FS4200 DK3200 SM4500 no time interested MMMAG gate see account",
"10-man EoE looking for experienced players",
"LFM Ulduar, looking for various experienced drivers",
"LFM AQ runs, looking for %role%",
"10-man UBRS, looking for %class% and %role%",
"New guild <Harem> preparing for TOC recruiting stable members. Level 80 stable players okay. Weekly 12 evenings 7.30-11 for 25-man activities. Interested private chat. Other times guild organizes 10-man for improvement!",
"HSL looking for tough T, can start 4=1",
"Selling [Infinite Dust]70 [Frostweave Cloth Roll]25",
"Scammer online, everyone come and watch...",
"Need love not WoW, looking for true love~~...",
"Shaman looking for Naxx... almost 80...",
"%zone% quest anyone?...",
"Zul'Drak Arena quest, need a %role%...",
"Starting Stockades, anyone wanna come?",
"LFG %instance%, need %role%. Let's snag some sweet loot!",
"Any groups running%instance%? I'm a DPS ready to roll.",
"%role% LFG for any dungeon. Have heals, will travel.",
"Looking for more for Strath UD. Come for the run, stay for the Baron's mount!",
"LFM Molten Core, need 2 %role%s. On Domo, let's get this fire party started!",
"Mage LFG %instance%. I bring portals and food, you bring the fun.",
"Hunter looking for group for %instance%. I promise my pet won't pull extra mobs... much.",
"LF1M UBRS, need rogue for those sweet lockpicking skills.",
"LFG Maraudon, Princess run. Let's turn her into compost.",
"Need a few more for Onyxia. Let's make some dragon stew.",
"Shadow priest LFG for any raid or dungeon. I'm like a Swiss Army knife, but with more shadow.",
"LF2M for %instance%, need DPS and %role%. Tryhards beware!",
"Warrior tank LFG, ready to face any challenge. Yes, even that one.",
"LFM for a chill %Instance% run. No rush, just fun and loot.",
"Rogue LFG. I've got lockpicks, poisons, and bad jokes.",
"LF1M %role% for quick UBRS. Keyholder here, let's unlock some chaos!",
"Paladin %role% LFG. Will turn undead and keep you alive, usually in that order.",
"LF3M for Lower Blackrock Spire. Need %role%. Let's get 'er done!",
"Resto druid looking for group. I can heal, tank, DPS, and make a mean salad.",
"LFM Naxxramas. It's like a party, but with more undead and frost damage.",
"Join <Cereal Killers>! We slay monsters before breakfast. Seeking night owls and early birds for dawn patrols in Azeroth!",
"<Darnassus Dance Party> is recruiting! If you can /dance and fight simultaneously, we want you! BYO disco ball.",
"Looking for a guild that appreciates fine wine and finer loot? 'Merlot Marauders' is now recruiting connoisseurs of chaos!",
"'Loot Hoarders Anonymous' needs you! We can't promise to cure your loot addiction, but we'll definitely enable it.",
"Join 'The AFKers'! Perfect for those who love to play, but have a life... sort of. Now accepting applications from fellow Alt-Tab experts.",
"'The Lag Vanquishers' are recruiting! If you've ever been killed by a lag spike, you're one of us. Revenge is best served in low latency.",
"Become a 'Goblin's Worst Nightmare' today! We spend gold faster than we make it. Currently seeking treasure hunters and auction house barons!",
"'The Thunder Bluff Kite Club' is looking for members! If you enjoy long falls and sudden stops, join us for our next 'flight'!",
"<Hogger's Heroes> wants you! Join us and be part of the legend. Requirements: Fearlessness and a love for respawn runs.",
"Calling all night owls! 'Midnight Raiders' is recruiting. Because the best loot drops after midnight... right?",
"'The Wandering Turtles' are slowly expanding! Join us if you believe slow and steady wins the race (to the loot).",
"'The Bank Alt Fashionistas' are here! Looking for members with a passion for inventory management and top-notch tabard style.",
"Be part of 'The Epic Failures'! We might not always succeed, but we fail in style. Now recruiting optimistic pessimists!",
"Join 'The Undergeared Underdogs'! We believe in challenging content – like trying to solo a raid boss. Gear optional, courage required!",
"'Grumpy Old Gnomes' is recruiting! Must be short, cranky, and have a passion for explosive engineering mishaps.",
"Are you 'Not Prepared'? Neither are we! Join us and Illidan won't be the only one disappointed. Now recruiting casual chaos creators!",
"WTB Teleport to Dal, 5g.",
"LF Teleport to Shattrath, 1g.",
"WTS |cffa335ee[Deathcharger's Reins]|r |cFFFFC0C0for a good price. Get your ride in style! Whisper me for details.|r",
"WTB |cff1eff00[Large Brilliant Shard]|r. |cFFFFC0C0Paying well, need for enchanting. PST with offers.|r",
"WTS |cffffffff[Runecloth]|r |cFFFFC0C0in bulk. Good for rep grind or first aid. Hit me up for a sweet deal!|r",
"LF Blacksmith to craft |cff0070dd[Arcanite Reaper]|r. |cFFFFC0C0I've got the mats and a tip ready. PST.|r",
"WTS |cffa335ee[Krol Blade]|r. |cFFFFC0C0Rogue's dream weapon. Whisper for price.|r",
"WTB |cff0070dd[Shadowcraft Bracers]|r. |cFFFFC0C0Completing my set. PST with price.|r",
"WTS stacks of |cffffffff[Thorium Bars]|r. |cFFFFC0C0Great for leveling engineering or blacksmithing.|r",
"Looking for a tailor to make |cffa335ee[Truefaith Vestments]|r. |cFFFFC0C0I have all the mats. Will tip generously!|r",
"WTS Epic Hunter BOE set. Get geared quick! PM for details and prices.",
"WTB |cff1eff00[Greater Eternal Essence]|r |cFFFFC0C0for enchanting. Need several, paying top gold.|r",
"WTS |cffa335ee[Spellpower Elixir]|r|cFFFFC0C0x20. Boost your DPS for tonight's raid. Bulk discount available!|r",
"LF Enchanter to do |cff0070dd[Crusader]|r |cFFFFC0C0enchant. I have the orbs and will tip. PST.|r",
"WTS |cffffffff[Major Healing Potions]|r. |cFFFFC0C0Be raid ready! Bulk deals available.|r",
"WTB |cffa335ee[Hand of Edward the Odd]|r. |cFFFFC0C0Name your price. Serious buyer here.|r",
"WTS |cffa335ee[Choker of the Fire Lord]|r |cFFFFC0C0from MC. BIS for many classes. PST offer.|r",
"WTB all your |cffffffff[Copper Ore]|r! |cFFFFC0C0Paying more than AH prices. Whisper me for quick gold.|r",
"WTS |cff0070dd[Robe of the Archmage]|r. |cFFFFC0C0Perfect for mages. Crafted and ready to wear!|r",
"LF someone to craft |cff0070dd[Titanium Spellshock Necklace]|r. |cFFFFC0C0Got mats + tip. PST if you can help!|r",
"LF tailor for |cff1eff00[Green Linen Shirt]|r. |cFFFFC0C0Got mats + tip. PST if you can help!|r",
"WTS |cffa335ee[Arcanite Bars]|r. |cFFFFC0C0Stock up for your legendary or other crafts. Whisper for price.|r",
"WTB |cff0070dd[Frozen Rune]|r |cFFFFC0C0for crafting. Paying well, need multiple. PST if you have any to spare.|r",
"When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
"Chuck Norris can divide by zero.",
"Chuck Norris doesn't sleep; he waits.",
"Chuck Norris can slam a revolving door.",
"Chuck Norris can unscramble an egg.",
"Chuck Norris's tears cure diseases. Too bad he has never cried.",
"Chuck Norris once counted to infinity. Twice.",
"Chuck Norris doesn't need mounts in Azeroth. He just walks faster than any epic mount.",
"Chuck Norris's Hearthstone has no cooldown. He's always home.",
"Chuck Norris's fishing skill is so high that even Murlocs ask him for tips.",
"Chuck Norris doesn't need a raid group. He is the raid group.",
"Chuck Norris's DPS is so high, bosses beg for mercy.",
"Chuck Norris can transmog gear from one expansion to another.",
"T-man's Night Elf Mohawk is the real reason for the Cataclysm.",
"T-man's Night Elf Mohawk once tamed a dragon with a single flex.",
"They once tried to implement Chuck Norris as a raid boss in WoW. However, during testing, nobody could survive the 'Roundhouse Kick' phase.",
"LF tailor to make |cff0070dd[Royal Moonshroud Robe]|r |cFFFFC0C0 . I have all the materials and will tip generously. PST for a quick deal!|r",
"LFG for Heroic Dungeons, need 1 healer and 1 DPS. Gear score 4500+ required. Whisper me for invite!",
"WTT |cff0070dd[Crusader Orb]|r |cFFFFC0C0  for|r |cff0070dd[Runed Orb]|r |cFFFFC0C0, 1:2 trade. Whisper me if interested!|r",
"Buying |cffFFFFFF[Heavy Borean Leather]|r |cFFFFC0C0  in bulk. Paying well above AH prices. PST with your offer!|r",
"LF Blacksmith to craft |cff0070dd[Tempered Titansteel Helm]|r |cFFFFC0C0 I have mats and will give a good tip. Whisper me!|r",
"Auctioning a rare pet |cff0070dd[Proto-Drake Whelp]|r |cFFFFC0C0 Starting bid at 5000g. PST to place your bid or buyout for 10k!|r",
"Selling cheap enchants! |cff0070dd[Superior Spellpower]|r |cFFFFC0C0,|r |cff0070dd[Greater Assault]|r |cFFFFC0C0 , and more. PST for prices and availability.|r",
"LF2M for Naxxramas 25, need 1 %role% and 1 %class%. Experience and proper gear required. Whisper for invite.",
"WTS |cff0070dd[Frozen Orb]|r |cFFFFC0C0x10, bulk discount available. Whisper me for a great deal!|r",
{"WTS enchanted boots, never run out of style.", "Do they also never run out of durability?", "Only if you avoid lava and dragons.", "Stylish and dragon-proof, a rare combo!", "Fashion meets function in Azeroth!"},
{"WTB a guide for the Auction House. I keep buying high and selling low.", "Is it a strategy or a curse?", "Let's call it a 'learning experience.'", "I can teach you, but I charge in gold!", "Auction House 101: Buy low, sell... oops."},
{"WTS legendary fishing pole. Only used once, scared off the fish.", "Do the fish tell tales about it?", "Yes, it's the one that got away!", "Catch of the day: epic fishing tales!", "Legendary pole, for legendary fish stories."},
{"WTB a pet that doesn't judge me for my poor battleground skills.", "Do pets even judge?", "Only with their little pet eyes.", "I have a non-judgmental turtle available.", "Find a friend who's slow to judge!"},
{"WTS rare cooking recipe. Results may vary.", "Does it require exotic ingredients?", "Only if you consider 'edible' exotic.", "MasterChef Azeroth edition.", "Cook at your own risk – or delight!"},
{"Looking to swap heroic tales. Mine involve mostly running away.", "Running away bravely, I hope?", "Bravely and with great speed!", "I'll trade you a tale of accidental heroism.", "Heroes or zeros, stories galore!"},
{"WTS [Bag of Holding]. May or may not hold your hopes and dreams.", "Capacity for existential crises?", "And a side pocket for regrets.", "Every adventurer's essential.", "Hold more than just items, hold possibilities!"},
{"WTB an alarm clock that works for early raid mornings.", "Do you sleep through boss fights too?", "Only the unimportant ones.", "I'll trade you for a rooster. Natural alarm!", "Wake up to Azeroth's calls of duty!"},
{"Selling maps to secret fishing spots. Fish tales included.", "Any legendary locations?", "Where the fish are as big as boats!", "Throw in a tall tale, and you've got a deal!", "Secret spots for epic catches!"},
{"WTB a joke book to entertain my guild. They're a tough crowd.", "How tough are we talking?", "Tougher than a level 1 boar.", "I have a book, but it’s all chicken jokes.", "Keep your guild clucking with laughter!"},
"LFG for any raid where my talent for accidentally pulling extra mobs is considered a skill.",
"Looking for %instance% group that doesn't mind if I confuse my healing spells with emotes.",
"LFM for %instance% run. Requirements: a sense of humor and a high tolerance for chaos.",
"LFG where my strategy of 'panic and randomly hit buttons' is an acceptable raid technique.",
"Looking for a group that appreciates interpretive dance as a form of battle strategy.",
"LFM for %instance%. Must be okay with me narrating the adventure like a fantasy audiobook.",
"LFG for an epic quest. Must bring your own snacks and a love for dramatic, unnecessary detours.",
"LF %instance% group where my pet's habit of aggroing extra mobs is seen as a fun surprise, not a problem.",
"Looking for a raid group where 'I thought it was a shortcut' is a valid excuse.",
"LFM for chill %instance% run. Bonus points if you can tell jokes while dodging boss mechanics.",
"Yo mama so fat, she exalted with McDonalds.",
"WoD was the best expansion ever.",
"Your momma's so fat chain heal hits her twice",
"Yo mama is so fat her 4pc set bonus was fries and a coke!",
"Your momma so fat she sat on the [Black Temple] and turned it into [Sunken Temple]!",
"Anyone up for a quick and easy %instance% run?",
"Anyone need help with any group quests?",
"|cff0070dd[Thunderfist's Mighty Hammer]|r |cFFFFC0C0WTS, best offer! It smashes! It crashes! It turns your enemies into ashes!|r",
"WTB |cffFFFFFF[Elixir of Giant Growth]|r |cFFFFC0C0Trying to look taller than my gnome girlfriend...|r",
"LF tailor to craft |cff0070dd[Robe of Eternal Night]|r|cFFFFC0C0. I provide mats. Will tip!|r",
"The end is nigh! Sell me your gear cheap and enjoy your final days!",
"WTB [Broken I.W.I.N. Button]. I heard it's a sure way to win PvP!",
"Anyone seen a rogue around here? He stole my heart... and my |cffFFFFFF[Bag of Shinies]|r",
"WTS lore explanations. Ever wondered why Thrall left? Or who shot first, Sylvanas or Greymane?",
"LF someone to just... talk to. About anything. WTB a friend?",
"WTS |cffFFFFFF[Gnomish Army Knife]|r |cFFFFC0C0It slices, dices, and makes julienne fries!|r",
"WTB directions to Orgrimmar. Keep getting lost... This map is useless!",
"LF chill people for a laid-back %instance% run. No rush, just fun!",
"think I finally found the perfect spot for meditation. So peaceful.",
"Anyone else love exploring old zones just for the nostalgia?",
{"Just found out my guildmate stole my loot. Traitor!", "This is why I don't join guilds. Too much backstabbing."},
"Sometimes, I just log in to listen to the game’s soundtrack. So relaxing.",
"Did you all hear about the guild leader from Vanquished who vanished with all the guild's funds?",
"I just like to watch the world burn. Anyone want to join me for some chaos?",
"I just logged in... what did I miss?",
"Do you enjoy snacks as much as you enjoy raids? Is your favorite boss fight against the Pizza Elemental in the Dining Room Dungeon? Well, do we have a guild for you! Join <Fat Kids Lag IRL>!  Whether you're as light as a feather or have gravitational pull, all are welcome!",
{"Why is it that every time I log in, there's a new villain in town? Can't we have peace for once?", "Because peace is boring! We need action, battles, and drama!"},
{"Did somebody say, |cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r|cFFFFC0C0?|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r"},
"LF someone to critique my |cff0070dd[Epic Poem of Guild Drama]|r. |cFFFFC0C0Will pay in emotional support!|r",
"Will trade rare cooking recipes for epic tales of your adventures!",
"Anyone up for a game of hide and seek in Dalaran? Winner gets a |cffFFFFFF[Bag of Mystery Trinkets]|r|cFFFFC0C0!|r",
"WTS advice on how to talk to quest NPCs. They're just misunderstood, really.",
"Anyone know how to get |cffFFFFFF[Sticky Glue]|r |cFFFFC0C0off my hands? Asking for a friend.|r",
"WTB [Map to Hidden Treasure]. I promise I won't spend it all in one place!",
"Anyone else's pet acting weird today? Mine just tried to sell me insurance.",
"LF group to explore [The Great Unknown]. Must bring own snacks and sense of humor!",
"Anyone seen a lost sheep around? Answers to the name Fluffy. Reward if found!",
"WTB [Mystery Potion]. The last one turned me green for a week. Want to see what's next!",
"LF fashion advice. Can't decide between |cff0070dd[Robe of the Cool]|r |cFFFFC0C0and|r |cff0070dd[Stylish Tunic]|r",
"Anyone want to swap ghost stories? I've got a chilling tale about the Haunted Gold Mine.",
"WTB [Ancient Artifact]. Doesn't matter what it does. I just like collecting old stuff.",
"LF someone to practice dueling with. Disclaimer: I'm terrible, but enthusiastic!",
"WTS |cffFFFFFF[Bag of Laughs]|r|cFFFFC0C0. Guaranteed to brighten your day or your money back!|r",
"Anyone up for a scavenger hunt in Stormwind? First clue is 'Where the King's Shadow Lies'.",
"LF group to test my new invention: |cffFFFFFF[Portable Campfire]|r|cFFFFC0C0. Great for spontaneous marshmallow roasts!|r",
"WTB [Elixir of Eternal Friendship]. Or just a regular friend. Either works.",
"Can someone teach me how to knit? Want to make |cffFFFFFF[Cozy Socks]|r |cFFFFC0C0for winter.|r",
"LF advice on pet training. My voidwalker keeps eating my homework.",
"Anyone want to join my book club? This week's read: 'The Lich King's Diary'. Spoiler: He's misunderstood.",
"WTB [Map to Secret Fishing Spot]. I swear I won't tell a soul!",
"LF fellow explorers for a trip to [Uncharted Island]. Must be okay with potential pirate encounters.",
"Is it just me, or does the |cffFFFFFF[Mysterious Floating Orb]|r |cFFFFC0C0look like it's judging us?|r",
"Anyone want to start a parade through the city? I've got a |cffFFFFFF[Box of Costumes]|r",
"WTB [Book of Calm Thoughts]. Trade chat is making my head spin today.",
"LF group to take silly screenshots with. Must enjoy costume changes and dramatic poses!",
"Anyone else collect weird stuff? I've got a whole tab of just left shoes...",
"WTB [Secret to Eternal Happiness]. Or just a slice of pie. Pie works too.",
}

return text