--[[
	FOR INITIALIZING TABLES/FUNCTIONS TO BE USED LATER ]]
INSTANCE_ZULAMAN = {}
INSTANCE_ZULAMAN.HEXLORD = {}
INSTANCE_ZULAMAN.JANALAI = {}
INSTANCE_ZULAMAN.NALORAKK = {}
INSTANCE_ZULAMAN.AKILZON = {}
INSTANCE_ZULAMAN.HALAZZI = {}
INSTANCE_ZULAMAN.ZULJIN = {}
